### ISSUE TITLE
Bug: Parsing () / () as "obsolete" instead of "operators"

### ISSUE THREAD

**Issue by arve0** [scratchblocks/scratchblocks#133]
I have this code (norwegian)

``` blocks
gå ((avstand til [Earth v]) / (50)) steg
```

which renders like this
![image](https://cloud.githubusercontent.com/assets/4810521/14674910/8e566ed0-0706-11e6-8447-af2fed218226.png)

The correct should be
![image](https://cloud.githubusercontent.com/assets/4810521/14674920/a10230b4-0706-11e6-8ce8-a8a1edad6add.png)

Whats strange, is that I'm [unable to reproduce at scratchblocks.github.io](http://scratchblocks.github.io/#?lang=nb&script=g%C3%A5%20%28%28avstand%20til%20%5BEarth%20v%5D%29%20%2F%20%2850%29%29%20steg). You can [debug this live here](http://arve0.github.io/oppgaver/scratch/astrokatt/astrokatt.html#steg-4-gravitasjon), scroll up about a page.

I'm using latest master, but have [built only nb translation](https://github.com/tjvr/scratchblocks/compare/master...arve0:no_build?expand=1).

Is scratchblocks.github.io using latest master?

**Comment by gahjelle** [comment]
This seems to be a problem for all operators blocks, not just the `(() / ())`. In http://arve0.github.io/oppgaver/scratch/gangemesteren/gangemesteren.html we are for instance using `*` and `=`.

**Comment by tjvr** [comment]
Which languages do you have loaded? Have you loaded both Norwegian and English, or just Norwegian?

**Comment by arve0** [comment]
Just norwegian.

**Comment by arve0** [comment]
Fixed when loading english too.

```js
scratchblocks.renderMatching('code.blocks', {
    languages: ['nb', 'en']
});
```

**Comment by tjvr** [comment]
I should probably fix this
