### ISSUE TITLE
Fix Diff tool for v3

### ISSUE THREAD

**Issue by gtoal** [scratchblocks/scratchblocks#180]
Is 'diff' still supported?

http://scratchblocks.github.io/diff/#114924085+114889952

fails to load on Chrome, fails to return from the compare on Edge (the new IE)

**Comment by tjvr** [comment]
Correct place, yes.

Supported, no. I'm probably not going to have time to fix it either!

**Comment by tjvr** [comment]
Closing since the diff tool is no longer supported.
