### ISSUE TITLE
The exported PNGs look blurry

### ISSUE THREAD

**Issue by BookOwl** [scratchblocks/scratchblocks#203]
![supported](https://cloud.githubusercontent.com/assets/13385064/18752199/a8f25f2e-80af-11e6-9e31-78241981b226.png)
As you can see, the exported PNGs are really blurry, as if they were scaled up from a smaller resolution.

**Comment by tjvr** [comment]
I'm sure someone already mentioned this, but I can't find the issue comment.

**Comment by arve0** [comment]
Possible solution: Upscale SVG before drawing to `canvas.toDataURL`?

**Comment by tjvr** [comment]
Yeah, you can create a larger offscreen canvas, and then scale() the context before drawing the SVG.

As mentioned in the other issue (which I can't find), the problem is simply to increase the DPI of the exported PNG.
