### ISSUE TITLE
I saw that you've updated the translations, why the project's page still shows older version. 

### ISSUE THREAD

**Issue by dnowba** [scratchblocks/scratchblocks#215]
Though  the Scratch Team have switched to Transifex instead, but the zh_TW language page you update from pootle is ok. When I browse your page, the translations seem to not update.
And when you have free time, Please help us to contact Scratch Team to renew the script in Scratch Forum and  Scratch Wiki. 
Thanks a lot.

**Comment by tjvr** [comment]
As I explained before, on #213, I'm going to wait until we've updated for the Transifex API. :)
