### ISSUE TITLE
Ring layout breaks for short stack blocks

### ISSUE THREAD

**Issue by ZenithRogue** [scratchblocks/scratchblocks#218]
If a block with 4 or less characters is put into a ring, the connection pegs are misaligned.

**Comment by tjvr** [comment]
Confirmed: <http://scratchblocks.github.io/#?style=scratch2&script=(%7Bmoo%7D%3A%3Agrey%20ring)%0A(%7Bmooo%7D%3A%3Agrey%20ring)%0A(%7Bmoooo%7D%3A%3Agrey%20ring>
![scratchblocks(1)](https://user-images.githubusercontent.com/639289/57587360-b099e600-74fb-11e9-95e2-0e07b9194e0d.png)

**Comment by NitroCipher** [comment]
lol, forgot i made this issue :P
