### ISSUE TITLE
exportSVGString() output contains invalid SVG

### ISSUE THREAD

**Issue by JackMorganNZ** [scratchblocks/scratchblocks#219]
Hi there! The following example uses the following Scratch syntax:

```
when flag clicked

say [Hello] for [2] secs
```

**[Open this diff for following description](https://www.diffchecker.com/RLwdz6kh)**

When I use NodeJS to create an SVG image from this text, I get the text on the left.
When I use the website viewer ([permalink](https://scratchblocks.github.io/#when%20flag%20clicked%0A%0Asay%20%5BHello%5D%20for%20%5B2%5D%20secs)) and 'Export SVG', the contents are on the right.

The main difference is regarding the element with `href="#greenFlag"`. The version on the right only has one `xmlns` specificed, but the version on the left has two `xmlns` attributes. This causes an error when viewing the SVG in a web browser:

![image](https://cloud.githubusercontent.com/assets/8001048/23689296/8be857f6-041e-11e7-8ed8-e12d8e73d924.png)

All elements from the green flag onwards aren't displayed. Deleting the text `xmlns="http://www.w3.org/1999/xlink"` before  `href="#greenFlag"` appears to fix the error.

I believe #217 is related to this.

**Comment by tjvr** [comment]
Yes, that sounds like #217. :/
