### ISSUE TITLE
Custom C-blocks?

### ISSUE THREAD

**Issue by iamunknown2** [scratchblocks/scratchblocks#220]
AFAIK, scratchblocks only generates C-blocks if it detects a certain string in the block (e.g `if <> then`).

Would it be possible to specify a syntax for generating custom C-blocks?

**Comment by tjvr** [comment]
`{}`

**Comment by liam4** [comment]
To clarify:

```
while <touching [mouse-pointer v] ?> {
	turn cw (15) degrees
} :: control
```

..yields this:

![while-demo](https://cloud.githubusercontent.com/assets/9948030/24583932/7cdfba3a-1731-11e7-91a4-cc3391f30aaa.png)
