### ISSUE TITLE
I cannot create a control scratch block

### ISSUE THREAD

**Issue by Syringegoogleplex** [scratchblocks/scratchblocks#222]

**Comment by liam4** [comment]
Perhaps you found an old guide that suggests you use `:: cstart`, `:: celse` and `:: cend`. Those are now obsolete, you'll need to do use this style of branching instead:

```
A {
	...
} B {
	...
} C :: control
```

![Demo](https://cloud.githubusercontent.com/assets/9948030/25273693/4fea2592-2663-11e7-8a37-8e232d9c5c69.png)

**Comment by tjvr** [comment]
Thanks @liam4! :-)

**Comment by Syringegoogleplex** [comment]
I meant as in a 'when game starts' block

> My Name: Damien Lesser
> Place of learning: Mounts Bay Academy
> Place of Registration:Room 45 MBA
> DfE Reference ( for my school ): 908/4172
> Registered school address:	Boscathnoe Lane, Heamoor, Penzance, Cornwall, TR18 3JT, UK

**Comment by tjvr** [comment]
@Syringegoogleplex Please don't leave personal information in comments—your email signature got in here.

**Comment by liam4** [comment]
Ah, you mean a "hat" block, I think. You can use the `:: hat` syntax for that, like this:

```
when game starts :: events hat
```

![Demo](https://cloud.githubusercontent.com/assets/9948030/25276373/383dc216-2670-11e7-9208-0ad543c0b169.png)
