### ISSUE TITLE
HTML Inline for stacked blocks

### ISSUE THREAD

**Issue by carlflor** [scratchblocks/scratchblocks#223]
Is it possible to render scratch blocks that are stacked together through inline in HTML?
Something like this:

```
<bl>move (10) steps next costume</bl>
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    scratchblocks.renderMatching("bl", {inline: true});
  });
</script>
```

Expected output:
![scratchblocks 1](https://cloud.githubusercontent.com/assets/4861092/25698005/bfefc022-30ef-11e7-85f5-aefc2c424574.png)

Actual output:
![scratchblocks 2](https://cloud.githubusercontent.com/assets/4861092/25698015/cf5a79bc-30ef-11e7-8a1a-94bf6fdf04e8.png)

[Test from Code Pen Here](http://codepen.io/carlflor/pen/pPrQxR)

**Comment by tjvr** [comment]
You could try omitting the `inline` argument, that might work. :-)

**Comment by carlflor** [comment]
I tried removing `inline: true`, but it still rendered separately. What I'm trying to figure out is to still render it inline but render as stacked blocks.

Here is the output upon removing `inline`
<img width="190" alt="screen shot 2017-05-04 at 5 54 52 pm" src="https://cloud.githubusercontent.com/assets/4861092/25698856/3c3f9b5e-30f3-11e7-98d2-c38656b663ff.png">

**Comment by carlflor** [comment]
@tjvr Here's a workaround I did though:

```
<div class="container" style="display: flex;">
  <bl>move (10) steps</bl> 
  <bl>next costume</bl>
  <bstack>move (10) steps <br> next costume</bstack>
</div>
<script>
  document.addEventListener("DOMContentLoaded", function(event) {
    scratchblocks.renderMatching("bl", {inline: true});
    scratchblocks.renderMatching("bstack");
  });
</script>
```

**Comment by tjvr** [comment]
Glad you solved it :-)

**Comment by carlflor** [comment]
thanks!
