### ISSUE TITLE
Online generator errors

### ISSUE THREAD

**Issue by MarcScott** [scratchblocks/scratchblocks#224]
The online generator at https://scratchblocks.github.io/ errors when trying to import scripts from shared projects
![error](https://user-images.githubusercontent.com/4516338/30864242-feb79f58-a2ca-11e7-8099-5998436446fe.png)

**Comment by tjvr** [comment]
Works fine for me!

Perhaps you're behind some sort of proxy that's messing with your internet connection?

Do you see anything in the JavaScript console?

**Comment by MarcScott** [comment]
It seems to be being blocked my Privacy Badger. This wan't an issue earlier
in the month. Might be some changes made to user tracking in Scratch.
