### ISSUE TITLE
Blocks interactivity

### ISSUE THREAD

**Issue by henriquehbr** [scratchblocks/scratchblocks#225]
i would like to know if:

- Is there a way of adding a close buttons inside blocks (like on firefox/chrome tabs)
- Moving the blocks inside a `div` (like on scratch website)

PS: **please**, if you can (or have some free time), implement these functions above

**Comment by tjvr** [comment]
Sorry, but I'm not going to do this.

You can always fork the project and implement your own changes, although if you want interactive blocks then surely you're better off with [scratch-blocks](https://github.com/llk/scratch-blocks)?

**Comment by henriquehbr** [comment]
so, one last question, i'm new to open-source:

> which file i should include in my website to embed [scratch-blocks](https://github.com/llk/scratch-blocks)?

there are just lots of random files and a poor documentation...

**Comment by tjvr** [comment]
I have no idea; try asking on the scratch-blocks repo, or perhaps the Advanced Topics on the Scratch Forums.

Part of open source is learning how to work things out yourself; it works better if everyone pitches in! Remember you’re getting it for free :-)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by henriquehbr** [comment]
thanks a lot, i really appreciate your help and your work

one last thing: 

> move to android, it's much better 👍
