### ISSUE TITLE
Feature request: Allow font-size to be passed in to SVG renderer as option

### ISSUE THREAD

**Issue by Jonic** [scratchblocks/scratchblocks#227]
We've been using scratchblocks on the new Raspberry Pi projects site (https://projects.raspberrypi.org), but we've found the text on the rendered SVG to be too small for our needs.

I've tried to find various CSS-based ways to up the font-size or scale the whole thing, but it doesn't seem to be possible without some hacky workarounds to ensure that they still fit in the flow of the document nicely.

How feasible is it enable the plugin to accept a base font-size as an option, which it then uses to calculate the sizes of the Scratchblocks? I've had a look at the code and there doesn't appear to be any hard-coded sizes, so I'm hoping that it would be possible to scale the values based on the font-size passed in.

What do you think? I'm hoping that it's not impossible!

**Comment by tjvr** [comment]
Given it’s an SVG, you should definitely be able to scale it up! :) If you can’t do it in CSS I guess I could add a scale option, that increases the size of the whole SVG by a constant factor?

**Comment by Jonic** [comment]
@tjvr That sounds perfect :) I’m happy to jump on a call to talk through what I’ve already tried if you like, but I think the most elegant solution would be to solve it in the plugin itself. Is there any way I can help out with this? I tried having a look, but nothing immediately jumped out at me.

**Comment by tjvr** [comment]
Ooh, we could reuse this for #203 too :-)

---

Here's what you need to do:

1. Call `newSVG` with a different initial size https://github.com/scratchblocks/scratchblocks/blob/master/lib/model.js#L958
2. Add some sort of scaling attribute to the `SVG.group(elements)` a few lines down from there (I think you can use a CSS `transform`?)
3. Add an option in `index.js`, and pass it through to `document.render()`.

I'm a bit busy at the moment, but feel free to shout if you need more guidance! :)
