### ISSUE TITLE
Generator is broken :-(

### ISSUE THREAD

**Issue by tjvr** [scratchblocks/scratchblocks#228]
The Scratch project URLs have moved again, and the new location doesn't support CORS :-(

Anyone know if there's a different URL we can use?

BTW the repo for the website is [here](https://github.com/scratchblocks/scratchblocks.github.io) if someone would be able to send a PR :)

**Comment by towerofnix** [comment]
>Anyone know if there's a different URL we can use?

No, sorry :)

Would a CORS proxy work? Those are cheaty:tm:, but I think one would make sense here.

**Comment by tjvr** [comment]
> Would a CORS proxy work?

That would probably cause me more pain--I used to get frequent bug reports about the generator not loading, which turned out to be someone's school proxy blocking things :(

**Comment by tjvr** [comment]
I'm going to close this in favour of #272.
