### ISSUE TITLE
Where are the shapes/colors of the blocks located?

### ISSUE THREAD

**Issue by NitroCipher** [scratchblocks/scratchblocks#230]
I am attempting to modify this project to conform to the shapes and colors of Scratch 3.0.  I can't seem to find where the shapes and colors are defined.

**Comment by tjvr** [comment]
Sorry! There are no plans to support Scratch 3.0 at this time :-)

**Comment by towerofnix** [comment]
If you still want to play around with it, though, the shapes are defined in [lib/draw.js](https://github.com/scratchblocks/scratchblocks/blob/master/lib/draw.js). Styles look to just be CSS rules defined in [lib/style.js](https://github.com/scratchblocks/scratchblocks/blob/master/lib/style.js).

**Comment by NitroCipher** [comment]
Blob8108 I think you misunderstand. I am working on my own fork of the project, not requesting something to be made

**Comment by tjvr** [comment]
I  kno!

**Comment by NitroCipher** [comment]
I have the current iteration of the project up at s3blocks.github.io if you want to take a look
