### ISSUE TITLE
Write blocks in english, translate them on render

### ISSUE THREAD

**Issue by javorekm** [scratchblocks/scratchblocks#231]
I am using translations for scratchblocks, but it seems to be very wild to rely on that translations as they are changing a lot (wild language :-) it's not a scratchblocks problem). It would be nice, if I can write the scratchblock code in english (original) and than parametrize the render to use actual translated version.

Now I am including scratchblocks into HTML page:

```html
    <!-- Scratchblocks-->
    <script src="https://scratchblocks.github.io/js/scratchblocks-v3.1-min.js"></script>
    <script src="https://scratchblocks.github.io/js/translations-all-v3.1-min.js" charset="utf8"></script>
    <script>scratchblocks.renderMatching('.language-blocks', {languages: ['cs']});</script> <!-- std blocks -->
    <script>scratchblocks.renderMatching("sb", {languages: ['cs'], inline: true});</script>  <!-- inline blocks -->
```

Is there a way to write blocks in english and translate them on render?
Thanks a ot.

**Comment by tjvr** [comment]
You can use `doc.translate(scratchblocks.allLanguages['cs'])` to translate a scratchblocks Document to another language.

To get access to the document, perhaps pass a custom `render` function to `renderMatching`:

```js
scratchblocks.renderMatching('.language-blocks', {
    languages: ['cs'],
    render: (doc, cb) => {
        // Translate immediately before rendering
        doc.translate(scratchblocks.allLanguages['cs'])
        doc.render(cb)
    }
})
```

**Comment by javorekm** [comment]
Thanks a lot!

A little typo, I must remove the `language: ['cs']` not to translate the source before rendering, so this works for me now:

``` javascript
scratchblocks.renderMatching('.language-blocks', {
    render: (doc, cb) => {
        // Translate immediately before rendering
        doc.translate(scratchblocks.allLanguages['cs'])
        doc.render(cb)
    }
})
```
