### ISSUE TITLE
Spaces are too large

### ISSUE THREAD

**Issue by zippee100** [scratchblocks/scratchblocks#234]
tried using blocks. got this instead:
![scratchblocks 2](https://user-images.githubusercontent.com/21120948/38318360-09a059a4-3827-11e8-899a-11129705391e.png)

**Comment by tjvr** [comment]
That sounds like a problem with your computer :)

**Comment by zippee100** [comment]
Sorry but i use the latest version, windows 10 and it was working previously when i was using this computer. please think of something else :)
