### ISSUE TITLE
Custom color tag broken

### ISSUE THREAD

**Issue by NitroCipher** [scratchblocks/scratchblocks#235]
I cloned this repo onto my own computer and attempted to use a custom color modifier (::#0055ff).  When any block has a color modifier like this is seems to stop allowing any new blocks to render. However this is not the case on your website. It will still work fine if you use an existing color such as ::motion

**Comment by tjvr** [comment]
You're quite right! Thanks for reporting 😊 

Fixed in 22348dd.
