### ISSUE TITLE
New translations release

### ISSUE THREAD

**Issue by aldreth** [scratchblocks/scratchblocks#240]
I see you [merged](https://github.com/scratchblocks/scratchblocks/commit/4216c3d80547da693cfdf6487697141eea8a8db0) @ninaszymor's new translations, but I also see you [removed](https://github.com/scratchblocks/scratchblocks/commit/5f92d1c0be45d4f532aea09af9d92bc0d8021baa) the `Makefile` that was used to build the translations. 

Is there a way to build & release `translations.js` & `translations-all.js` - and sorry if I'm asking a question while you're in the middle sorting this, but your day job is taking precedence (for obvious reasons)! And is there anything I can do to help?

**Comment by tjvr** [comment]
Hey @aldreth,

>  sorry if I'm asking a question while you're in the middle sorting this, but your day job is taking precedence (for obvious reasons)

That's pretty much the case I'm afraid! :)

The `Makefile` has been replaced with some new scripts, hopefully the new translations have made their way into <http://scratchblocks.github.io/v3.2/>. Can you confirm whether that's the case? :)

**Comment by tjvr** [comment]
> hopefully the new translations have made their way into http://scratchblocks.github.io/v3.2/.

Whoops, nevermind that; I'll need to merge #238 first!

**Comment by aldreth** [comment]
👍 I was about to say the source of http://scratchblocks.github.io/v3.2/ includes `<script src="/js/translations-all-v3.1-min.js" charset="utf8"></script>` - so no new translations yet.

**Comment by tjvr** [comment]
I think this is now resolved :)
