### ISSUE TITLE
Fix options ordering

### ISSUE THREAD

**Issue by Jonic** [scratchblocks/scratchblocks#242]
See: https://github.com/scratchblocks/scratchblocks/blob/master/syntax/syntax.js#L782

In this function we attempt to merge the user's `options` with a set of defaults. I noticed that no matter how many extra languages I specified in my `options`, the `extend` function threw them out and stuck with the default, which breaks scratchblocks for anyone wishing to use any language other than English.

```javascript
function extend(src, dest) {
  return Object.assign({}, dest, src)
}

var defaultOptions = {
  inline: true,
  languages: ['en'],
}

var options = {
  languages: ['de', 'fr', 'it', 'ja'],
}

extend(defaultOptions, options)

/*
  Expected outcome:
  {
    inline: true,
    languages: ['en', 'de', 'fr', 'it', 'ja'],
  }

  Actual outcome:
  {
    inline: true,
    languages: ['en'],
  }
*/
```

I've put together a Codepen that illustrates this too: https://codepen.io/Jonic/pen/odVQOL

The Codepen example also contains a proposed solution, using the (n-deep-merge package)[https://github.com/eclifford/n-deep-merge] - I've put together these changes in #241, so I'll put together a PR that cherry-picks those changes so we can merge it separately.

@tjvr Does that explain things well enough? :)

**Comment by tjvr** [comment]
That's for explaining!

I think the bug here is actually that the arguments are flipped: it should be `extend(options, { ... })`.

Then it would be consistent with the usage in `draw.js`. The intent is that with expressions like

```js
extend(props, {
        x: 0,
        y: 0,
```

**Comment by tjvr** [comment]
Aha! The intent is that anything passed in with `options` will override anything that's there.

So you need to pass in `en` explicitly in this case. :)

**Comment by tjvr** [comment]
Sounds great, thanks! And thank you for spotting this
