### ISSUE TITLE
"Stop other scripts in sprite" is cap block

### ISSUE THREAD

**Issue by chexbox** [scratchblocks/scratchblocks#246]
This was somehow changed in a recent update, as it is not this way on the wiki.

**Comment by towerofnix** [comment]
@chexbox I'm a little confused? In the latest versions of both Scratch 2.0 and 3.0, "stop other scripts in sprite" is still a stack block, and this matches scratchblocks.github.io, where it's always a cap block unless the input is "other scripts in sprite".

**Comment by chexbox** [comment]
No, the error is that on the scratchblocks website it remains a cap.
![screenshot 2018-05-30 at 07 58 13](https://user-images.githubusercontent.com/31783961/40721499-39dbae1e-63df-11e8-9073-b49053d463b9.png)

**Comment by towerofnix** [comment]
@chexbox Ahh, right, that's in 3.2. I was testing with 3.1. Oops!
