### ISSUE TITLE
distinguishing between blocks of similar syntax

### ISSUE THREAD

**Issue by NitroCipher** [scratchblocks/scratchblocks#251]
I want to get back into continuing s3Blocks, and I am wondering how you managed to distinguish
```[abs v] of ()``` from ```[value v] of ()```

(currently trying to distinguish between graphic and audio effects)

**Comment by tjvr** [comment]
I have a little code to do this on a branch 🙂

The trick is for each language to keep a list of the valid inputs to one of the blocks (e.g. `["pitch", "pan left/right"]`), and then just check if the menu  option is in that list.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
