### ISSUE TITLE
Model.js needs to be independent between scratch2 and scratch3

### ISSUE THREAD

**Issue by NitroCipher** [scratchblocks/scratchblocks#254]
I have found that you need to modify model.js for scratch3 in several aspects. Most notably while adjusting block padding as shown below, along with adjustments made for the fonts used in Scratch 3
```
Block.padding = {
    hat: [20, 6, 8],
    "define-hat": [20, 8, 10],
    reporter: [5, 3, 2],
    boolean: [5, 2, 2],
    cap: [11, 6, 6],
    "c-block": [8, 6, 5],
    "if-block": [8, 6, 5],
    ring: [10, 4, 10],
    null: [11, 6, 6],
  }
```

**Comment by tjvr** [comment]
But it already is? I separated out `syntax/model.js` from `scratch2/blocks.js` a while ago :) The padding for instance now lives on `BlockView.padding` in the scratch2 package.

**Comment by NitroCipher** [comment]
alright, cool! _\*hasnt looked at the updated codebase fully yet\*_

**Comment by tjvr** [comment]
I'm going to close this, but feel free to ask questions about the codebase and/or raise bugs! 😊 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
