### ISSUE TITLE
Scratch 3 obsolete block colors

### ISSUE THREAD

**Issue by tjvr** [scratchblocks/scratchblocks#259]
We should set sensible border colors, to make it easier to see what you're typing.

![scratchblocks 1](https://user-images.githubusercontent.com/639289/49401755-fcbc4f80-f73f-11e8-94bc-c421d840981f.png)

**Comment by NitroCipher** [comment]
In s3blocks, I cheaped out, and set the border to a transparent black. it looks decent, but I will probably change it later
