### ISSUE TITLE
Set min-width for hat blocks

### ISSUE THREAD

**Issue by 77Lucky7** [scratchblocks/scratchblocks#261]
If you input something like,
`::sound hat`,
the hat block will look glitched.

Same for the ring blocks, but instead of being glitched out, they look like ovals.
`::sound ring`

**This is @LuckyLucky7 from Scratch.**

**Comment by tjvr** [comment]
We should probably set a minimum width for hat blocks. I'm not sure what's appropriate to use, since none of the official Scratch 3 blocks are short enough to trigger one!

I'm not going to do any work on ring blocks for the Scratch 3.0 renderer :)
