### ISSUE TITLE
Transpile scripts for IE11

### ISSUE THREAD

**Issue by Jonic** [scratchblocks/scratchblocks#262]
@tjvr Hello! Been a while since I've been over here - I believe we spoke briefly about this earlier in the year, but I'm creating an issue so it's tracked and we can discuss it if necessary.

Earlier in the year I merged this update that allows a website to consume Scratchblocks as a JavaScript module (587b78a84314720fa62b7e89a81725995cbf03a5). I'm now ready to update our implementation on the projects site, but before I do I need to update the build process to introduce a transpilation step which will enable IE11 support for us once again.

It shouldn't involve any updates to the actual code, only `package.json`, so your work should be completely unaffected. It should also be easy enough to merge into your work on the Scratch 3 compatibility update.

Does all of this sound ok? I'll get a PR together today and we can talk it over if you have any concerns or reservations, but we really need IE11 support again, and I think this is the easiest way of achieving that :)

Also FAO of @martinohanlon and @conoramurphy

**Comment by Jonic** [comment]
@tjvr I might need to speak to you about the new version you're working on, as it looks like your built filenames differ from the current ones, and I'm also a little confused about the translations files too - the README refers to files that don't exist anymore, and I think there are some redundant `npm` scripts too! When would be a good time to chat about this?

Good news is I'm getting dead close to having this done. I think I need a little help figuring out this last bit is all. If you're working on it tonight please email me at [my github username]@[the domain on my Github profile] and I'll pick it up when I'm at home. I can jump on a call to talk it over if you're around. If not then please let me know when works for you - I'm not sure how you're fitting this in around your day job! Ta! :)

**Comment by tjvr** [comment]
Hey @Jonic,

Sorry for the delay—I didn't pick up GitHub notifications for a couple days (and work's been a bit crazy...)

**IE11**
I don't have any strong opinions on changing the build for IE11. I would slightly prefer to avoid a transpilation step: if it's easy to just update the source code to remove whatever feature IE11 doesn't support, I'm happy to do that!

**Build**
Regarding changes to the build system: I'm not sure why the filenames would have changed.

We merged in #238 to update the translations, which was necessary to get them from Transifex. That was merged a month _after_ you merged 587b78a / #243.

I'm not aware of any scripts in `package.json` which aren't required (but I could well be wrong!).

**Comment by Jonic** [comment]
@tjvr Hey Tim, no worries for the wait - I appreciate you’re very busy! :)

If you’d rather avoid a transpiration step then I’lol shelve what I’ve done and I guess this is now a request for IE11 support. And that being the case, my other comments about translations and package.json scripts are now no longer relevant!

Thanks for your help with this! I know the content team have been hoping for IE11 support to be added back in again so they can finally make use of the diff mode, so they’ll be dead happy to hear it’s being taken care of! If there’s anything I can do let me know.

Thanks!

**Comment by martinohanlon** [comment]
@tjvr @jonic just to add to this IE 11 support is essential (as much as it pains me) and a blocker to us taking a new version of scratchblocks. Any view on whether this is a simple thing to fix?

**Comment by tjvr** [comment]
@jonic Echoing Martin's comment above: do you know what exactly doesn't work in IE11? And is it easier to add a transpilation step or to fix it directly? 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jonic** [comment]
@tjvr @martinohanlon It's hard to say for definite how much code there is that IE11 doesn't like, because it stops reporting after finding the first thing it finds. I'm going to run it through an eslint package that checks for browser compatibility, hopefully that will help us get closer. I'll branch again off master and see if I can get an idea of what needs to be fixed, and hopefully the fixes themselves if they're not too numerous!
