### ISSUE TITLE
Scratch 3 - variables arent render in orange blocks

### ISSUE THREAD

**Issue by martinohanlon** [scratchblocks/scratchblocks#267]
The following code:

```
turn cw (my variable) degrees
```

Creates:

![image](https://user-images.githubusercontent.com/2329501/50098462-e15b4500-0213-11e9-8b87-44092ff5dbfc.png)

Which appears to be missing the variable formatting e.g.

![image](https://user-images.githubusercontent.com/2329501/50098494-f6d06f00-0213-11e9-9e23-3eef9c4e12a5.png)

The equivalent in scratchblocks(2) would be:

![image](https://user-images.githubusercontent.com/2329501/50098538-0e0f5c80-0214-11e9-8864-adf264b55678.png)

This was consistent for all blocks I tried.

**Comment by martinohanlon** [comment]
I suspect this is also related, there is a similar issue using "my blocks" and internal parameters.

This code:

```
define say something (words)
say (words)
```

Creates:

![image](https://user-images.githubusercontent.com/2329501/50099008-fe444800-0214-11e9-9da7-bd06acfdfced.png)


Which should be:

![image](https://user-images.githubusercontent.com/2329501/50098992-f5537680-0214-11e9-845a-576a6931a4ae.png)

**Comment by NitroCipher** [comment]
This is a bug related to the new parsing of round parentheses from #252 
currently the only way I have found to use the ```::variables```

IE ```turn cw (my variable ::variables) degrees```

**Comment by NitroCipher** [comment]
The parser will however recognize a variable reporter if the variable is declared elsewhere in the block script.

**Not declared:**
![scratchblocks](https://user-images.githubusercontent.com/11393734/50099682-53b43100-01e4-11e9-994e-bf9aca3582bc.png)
**Declared:**
![scratchblocks](https://user-images.githubusercontent.com/11393734/50099673-4ac35f80-01e4-11e9-8de9-bb649f3812e3.png)

**Comment by tjvr** [comment]
So as @NitroCipher suggests, this is a deliberate design choice. Since Scratch 3.0 variables are round, I've modified the parser to recognise round inputs as strings; I think it might be confusing to transcribe blocks otherwise.

Variables will be recognised if there's a "set variable to" or "change variable by" block elsewhere in the source. You can also use the `::variables` tag to explicitly force variables.

I'm very interested in feedback on this design decision; would it be less confusing to require square brackets for strings? (They would of course still be rendered as round.)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NitroCipher** [comment]
For compatibility issues alone, I think it would be less confusing to just use square brackets. Additionally, a lot of scratchers unfamiliar to scratchblocks might not know about modification syntax as well

Side note: should ```::variable``` be an alias of ```::variables```?

**Comment by martinohanlon** [comment]
I also think it would also be less confusing to render strings as square brackets, having 2 defined input methods for strings `[]` and variables `()` sounds sensible, with the added benefit of maintaining compatibility

If you are worried about transcribing, what about adding in the ability to use quotes inside a round input to denote a string e.g.

```
say [Hi]
```

or

```
say ("Hi")
```

**Comment by NitroCipher** [comment]
quotes are commonly used inside of projects, so that would introduce more issues with the parser

**Comment by martinohanlon** [comment]
> quotes are commonly used inside of projects, so that would introduce more issues with the parser

I suppose, in which case you could use the `[]` brackets.

**Comment by tjvr** [comment]
I think the existing `[ ]` syntax is the best alternative.

I'd love to gather more feedback on this change, but for now I'll simply revert the parser dialect used on the demo page.

The parser now supports two dialects, similarly to how there are two renderers, so reverting to the default dialect will disable the new code. Once we've confirmed this decision, I'll probably remove the new dialect entirely. 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by martinohanlon** [comment]
Sounds good to me.

**Comment by tjvr** [comment]
I've updated the homepage to always use the "classic" dialect. This means `say (foo)` will now render as a variable, even when rendering to Scratch 3.

I've also made the new homepage the default, and updated the translator to use Scratch 3 blocks. 🙂
