### ISSUE TITLE
Can you tell us how to use Scratch3.0 blocks render in HTML?

### ISSUE THREAD

**Issue by dnowba** [scratchblocks/scratchblocks#269]
I have seen the README.md and follow the usage in HTML, but seems that the method only work in Scratch 2.0. Please tell us the right way to render Scratch 3.0's blocks.

**Comment by tjvr** [comment]
Merry Christmas! 🎄

I should be updating the Readme in a few days. In the meantime you can try passing `{style: "scratch3"}` to renderMatching 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
Hey, does this help? :)

The interface for using scratchblocks has changed. It now looks something like this:

```js
// Parse the source code
var doc = scratchblocks.parse(source, {
  languages: obj.lang ? ['en', obj.lang] : ['en'],
})

// Create a DocView with your chosen style
var docView = scratchblocks.newView(doc, {
  style: 'scratch3', // Or 'scratch2'
})

// Render to an SVG
var svg = docView.render()

// Scratch 3 is zoomed out by default, so you probably want to do the same
svg.style.transform = 'scale(0.675)';
svg.style.transformOrigin = '0 0';

// Add that SVG to your page, etc
document.body.appendChild(svg)
```
