### ISSUE TITLE
Generator doesn't work on Scratch 3.0

### ISSUE THREAD

**Issue by McSinyx** [scratchblocks/scratchblocks#272]
Seemingly new version of Scratch updated the storage location for project, thus generator still fetch scripts from before Jan 2. I'm not sure how to solve but I'd be glad to help if there's anything I can do.

**Comment by tjvr** [comment]
I imagine we'll need to update the generator to understand the new sb3 storage format unfortunately 😔

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Huy-Ngo** [comment]
It is weird that *some* of the projects can be converted and some cannot. Probably the ones that can be converted weren't modified after the new update.

**Comment by Huy-Ngo** [comment]
I just give a peek at one of a new JSON file for a *.sb3 and apparently the properties and values are encrypted. In addition, it looks like the structure of the JSON file is different, too. Unsurprisingly it doesn't work...

**Comment by benjiwheeler** [comment]
@Huy-Ngo I **think** that there is nothing encrypted in `.sb3` files. They're zipped, so you need to unzip them, and then they have asset ids that use md5 hashes as the filenames, and block instances are uniquely identified using strings like "_sVg+ALFy:6A|#}hI^Tg".

**Comment by NitroCipher** [comment]
I have started work on it! I'll update documentation later, and also convert it to a proper site, rather than a userscript

https://github.com/s3blocks/s3bGenerator

**Comment by NitroCipher** [comment]
The generator is already almost complete! the only thing left is nested reporters, but otherwise, everything seems to work!

**Comment by NitroCipher** [comment]
I just finished up the reporters, now all that is left is the custom blocks. I also built a standalone page for the generator, rather than just the userscript

Try it out:
https://s3blocks.github.io/generator/?id=101720316

**Comment by NitroCipher** [comment]
@tjvr Try it out if you want!

**Comment by posollid** [comment]
I've encountered an issue with the exported svg-files generated by the s3blocks generator. The generated file looks completely fine in chrome and GIMP, but is incorrectly displayed when opened in inkscape and powerpoint (365-version which supports svg).

I generated another svg-file using the sblocks generator with the same exact scratch code / blocks and it displayed correctly in all of the above mentioned programs.

**Comment by NitroCipher** [comment]
This seems to be an issue with the svg renderer in inkscape, but im really not sure what is happening. Definitely super strange

![image](https://user-images.githubusercontent.com/11393734/54874031-31b4e680-4db1-11e9-9e80-a9959cc7c461.png)

**Comment by posollid** [comment]
I agree, although the same issue happens with PowerPoint and also online converters I’ve tried like convertio.co to convert to other vector image file types... Also I don’t have this issue with the svg generated by the scratchblocks site (using 3.0 blocks).

So possibly the solution lies somewhere in the differences between the two svg-export-methods?

**Comment by tjvr** [comment]
Closing since the generator is no longer supported.
