### ISSUE TITLE
Scratch 3 rendering issues

### ISSUE THREAD

**Issue by Jonic** [scratchblocks/scratchblocks#273]
Hi @tjvr - happy new year, if it's not too late in the month to be saying that!

We've (finally) deployed the updated Scratchblocks script to the Raspberry Pi Projects site, but one of our content editor (@martinohanlon) has noticed some inconsistencies with the rendering of the new Scratch 3 blocks. I don't think it's my implementation of the script that's caused the issue, so I've opened this issue.

From Martin:

> I have started to update our projects to use the latest version of scratchblocks and have noticed some inconsistencies when compared to the scratchblocks website.
> 
> Specifically in blocks which include "arrows" such as forever and turn blocks.
> 
> ![51235893-95adcf80-1968-11e9-96a5-917e33c3d208](https://user-images.githubusercontent.com/11579/51248362-c6513180-1987-11e9-8ff7-568629d7778e.png)
> 
> The arrows on the projects site look like the Scratch 2 arrows. Could we be using an older scratchblocks code base?
> 
> There is also a difference in the size of the blocks, although this is not necessarily a problem if the blocks are bigger.

Did you work on the rendering side of things any more since I merged the IE11 fix and translations build script? Your dev version number appears to be 4.0.0, but I'm not sure if that's what we were still aiming towards after my stuff got merged. If you could help me get an idea of what's happening and what we can do to fix this then that'd be ACE. Thanks :)

**Comment by NitroCipher** [comment]
Are you directly using the external bundle file? Or are using a build you compiled yourself?

**Comment by Jonic** [comment]
@NitroCipher It's the result of the `npm run start` command. The bundle is generated by Rollup and dropped in the `build` directory. I copied it from there and we're hosting it ourselves. I was going to deploy the current version (3.2) to http://scratchblocks.github.io, but there's already a 3.2 script on that domain, which isn't the same version. I didn't get chance to talk to Tim about the version numbering inconsistency before Christmas, so perhaps that's something that's needed here too!

**Comment by NitroCipher** [comment]
Can I get a link to the site it is deployed on?

**Comment by Jonic** [comment]
@NitroCipher Yes of course - sorry! The live version of the image above is this: https://projects.raspberrypi.org/en/projects/lost-in-space/5

You'll have to open the "I need a hint" box and advance to the second step in the hint to see the issue.

**Comment by Jonic** [comment]
@NitroCipher Also, just noticed you linked me to the v4 script - AFAIK (and maybe @tjvr can confirm this), that script is now actually behind the 3.2 script he and I released just before Christmas, so I think maybe the master branch here needs to be updated with the work that's continued in that v4 script? I'm not too sure!

**Comment by NitroCipher** [comment]
Afaik, the scratchblocks.github.io site uses the v4 script. I will check in a minute

**Comment by Jonic** [comment]
@NitroCipher The Scratch 3 demo there does, yeah. I think there's maybe some confusion about that v4 version, and the current `master`. They appear to have different rendering, but I won't know for certain without @tjvr's help!

**Comment by NitroCipher** [comment]
i locally replaced your bundle file, and that does not seem to be the issue. I will look more later. Can you send a zip of the plugin you have deployed?

**Comment by Jonic** [comment]
@NitroCipher Sure thing: [rpi-projects-scratchblocks.zip](https://github.com/scratchblocks/scratchblocks/files/2765279/rpi-projects-scratchblocks.zip)

Thanks for your help! FWIW, I just pointed our projects site at the v4 script and the blocks are still coming out bigger than the demo page shows them. So it might actually be our implementation - I just can't see what right now!

**Comment by tjvr** [comment]
Do you parse the script once, and then render the blocks twice, once in each language? Which style do you render first?

I'm wondering if there's some accidental mutation going on...

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NitroCipher** [comment]
I have no idea what is happening. In your build, you have the 2.0 icons in the hardcoded, but not the 3.0 ones.

**Comment by tjvr** [comment]
I think I've figured it out 🤦‍♂️ I would guess that the `<use href="#loopArrow">` doesn't work when you have both Scratch 2 and Scratch 3 scripts in the same document.

**Comment by Jonic** [comment]
@tjvr It's a weird one for sure - I'm having trouble replicating it locally!

I have noticed that if I have Scratch 2 and 3 on the same page, and the Scratch 3 appears in the DOM after the Scratch 2, then the arrow images are misaligned on the Y axis, but it's the correct graphic. This case in the "lost in space" project is different, because there's no Scratch 2 in the rest of the page or project. So I've no idea why it's using the old arrow image.

Is there an easy way to fix this? Maybe some namespacing of the `#loopArrow` reference or something? I'll try that today and submit a PR if that fixes it :)

**Comment by tjvr** [comment]
I'll try and have a look 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
Fixed in d9322cf! :-)
