### ISSUE TITLE
the dash in `-Effekt` does not get rendered (and break things)

### ISSUE THREAD

**Issue by aoloe** [scratchblocks/scratchblocks#278]
The German translation for

```
set [whirl v] effect to (mouse x)
```

is 

```
  setze [Wirbel v] -Effekt auf (Maus x-Position)
```

But the `-` before `Effekt` does not get rendered and seems to break things.

I could get a sane result by using

```
  setze [Wirbel v] Effekt auf (Maus x-Position) :: looks
```

**Comment by tjvr** [comment]
Thanks! It turns out we're not translating the sound effect arguments properly. :)
