### ISSUE TITLE
Support for icons in custom Scratch 3 blocks

### ISSUE THREAD

**Issue by dalelane** [scratchblocks/scratchblocks#280]
I'd like to use Scratchblocks to document some custom extension blocks for Scratch 3.

My blocks include a custom icon. 

Is there any way in scratchblocks to specify an icon to use for custom blocks (in the same way that, for example, the pen icon is shown for blocks like `set pen color to [#00FF00]`), please?

**Comment by tjvr** [comment]
I'm afraid there isn't a way to do that right now!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
