### ISSUE TITLE
Employ ESLint

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#283]
If acceptable, I'd like to contribute to do this issue.

ESLint: https://github.com/eslint/eslint
JavaScript Style Guide: https://github.com/standard/standard

**Comment by tjvr** [comment]
Hey, thanks for your interest in contributing. I've already set up Prettier to format the codebase (see `npm run fmt`). What advantage would ESLint give?

**Comment by Smrman** [comment]
Prettier just formats your code while ESLint gives you tips on how to modernize your code (use the latest ES6 features, good practises, etc..)
I'd recommend you to use ESLint too since it's a great tool, can't hurt ;)

**Comment by exKAZUu** [comment]
@tjvr Sorry for the late response.

ESLint is a linter for warning and fixing code fragments which violate configurable rules (i.e. coding conventions).
Please check the advantages by seeing my draft PR (#286). The reason why I would suggest to use ESLint is that the current code uses a bit old JS syntax like `var` v.s. `let` + `const`.

Though ESLint is a de facto standard, there are too many configurable rules. [JavaScript Style Guide](https://github.com/standard/standard) is one of the widely accepted coding conventions, so I've selected it.

Note I don't intend to control the coding conventions. It's just an idea :)

**Comment by exKAZUu** [comment]
I understand this issue is not needed now. If needed, I can help anytime.
