### ISSUE TITLE
Translator doesnt translate blocks inside C blocks

### ISSUE THREAD

**Issue by martinohanlon** [scratchblocks/scratchblocks#287]
We just noticed that the translator doesnt translate anything which is inside a C block.

e.g.

https://scratchblocks.github.io/translator/#?lang=nl&script=forever%0Amove%20(10)%20steps%0Aend

![image](https://user-images.githubusercontent.com/2329501/57164905-70e14900-6ded-11e9-9c55-dae7e470eda5.png)

I dont know if this is a recent issue, or has always been like this.

**Comment by tjvr** [comment]
Good spot, thanks!

This should be fixed now: [here's an example](http://scratchblocks.github.io/translator/#?lang=de&script=when%20flag%20clicked%0Aif%20%3Cmouse%20down%3F%3E%20then%0Astamp%0Aelse%0Aclear%0Aend) :-)
