### ISSUE TITLE
`postinstall` should be removed in package.json

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#294]
When installing `scratchblocks` in a node project, `scratchblocks`'s [postinstall](https://github.com/scratchblocks/scratchblocks/blob/master/package.json#L25) is automatically executed and `rollup` causes an error.

The reason why the error occurs is that the uploaded `scratchblocks` package doesn't include `locales-src` as follows.

```bash
$ ls node_modules/scratchblocks
browser.js  build/  index.css  index.html  index.js  LICENSE  locales/  package.json  README.md  rollup.config.js  scratch2/  scratch3/  syntax/
```

However, `postinstall` seems unnecessary because the uploaded `scratchblocks` package has already included minified javascript files as follows. There is no need to build `scratchblocks` from a node project just depending on `scratchblocks`.

```bash
$ ls node_modules/scratchblocks/build/
scratchblocks.min.es.js  scratchblocks.min.es.js.map  scratchblocks.min.js  scratchblocks.min.js.map  translations.js  translations-all.js
```

So, I would recommend to remove `postinstall` script from `package.json` and to use `build` script explicitly in daily deevlopment if needed.

**Comment by tjvr** [comment]
I believe @Jonic set this up; what do you think? 🙂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jonic** [comment]
@tjvr @exKAZUu Yeah that makes sense to me. If it's not working then I obviously failed at whatever it was I was trying to do! I don't removing it is going to cause any problems! :)
