### ISSUE TITLE
Fix or remove #server-side-node in README

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#298]
The content of https://github.com/scratchblocks/scratchblocks#server-side-node is currently not correct. So I believe we should fix or remove it.

Btw, I've confirmed that `scratchblocks` can work on Node.js. It is still useful for me because SVG images generated via Node.js seem identical with ones generated via a browser on the same PC (though #293).

I'd like to improve README by writing instructions to make work `scratchblocks` on Node.js or just by removing the content. @tjvr What PR should I create?

**Comment by tjvr** [comment]
I would remove it. As I [wrote previously](https://github.com/scratchblocks/scratchblocks/issues/293#issuecomment-492960885):

> we care a lot about text metrics, and since those are specific to your installed fonts it doesn't make sense to generate SVGs on the server which may be rendered with different fonts installed.
