### ISSUE TITLE
Color of my block is different from Scratch 3.0

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#303]
- Scratch 3.0
  ![image](https://user-images.githubusercontent.com/436237/60409122-1c93f300-9bfd-11e9-8025-dff8168655c0.png)
- scratchblocks
  ![scratchblocks](https://user-images.githubusercontent.com/436237/60409137-32a1b380-9bfd-11e9-92a6-485114b763fc.png)

**Comment by NitroCipher** [comment]
`my block` is not a _real_ block. It is the placeholder text for a custom block.

However, if you type `define my block`, all appearances of `my block` will become pink
![scratchblocks](https://user-images.githubusercontent.com/11393734/60410535-790bf980-9b8e-11e9-9794-a6958b3c624d.png)

**Comment by exKAZUu** [comment]
Thank you for the comment! I understand.
Hm, I sometimes want to show a fragment of a program excluding a definition for the sake of brevity.
Is there any workaround to make `scratchblocks` recognize blocks as defined ones?

**Comment by NitroCipher** [comment]
absolutely! You can do the custom block color using  `my block ::custom`, or any color with `my block ::#FF00FF`

**Comment by exKAZUu** [comment]
Oh, I didn't know such a notation 😓 
Thank you for your help!

**Comment by NitroCipher** [comment]
No problem, glad to help
