### ISSUE TITLE
The Chinese translation of "effect" blocks are wrong

### ISSUE THREAD

**Issue by plntsmtphr** [scratchblocks/scratchblocks#307]
"effect" should be ”特效“ in Chinese instead of "音效". 
e.g. 

- "change (color v) effect by (24)" should be "将(颜色 v)特效增加(25)".
-  "set (color v) effect to (0)" should be "将(颜色 v)特效设为(0)".
- "clear graphic effects" should be "清除特效".

**Comment by tjvr** [comment]
We use translations from [scratch-l10n](https://github.com/LLK/scratch-l10n), which come from Transifex, so the translations should always match Scratch.

I've just updated the translations, so hopefully this will be resolved the next time I deploy the website.
