### ISSUE TITLE
Can please provide an example of usage in HTML?

### ISSUE THREAD

**Issue by JorgeNachtigall** [scratchblocks/scratchblocks#309]
Hi,

I'm build an real time monitor tool for Scratch projects and I'm trying to use scratchblocks to render the code that I've receive from my server, but I can't understand how to use this lib.

I've imported `<script src="https://scratchblocks.github.io/js/scratchblocks-v3.0-min.js"></script>`

and already placed `scratchblocks.renderMatching('pre.blocks');` on my .html file but nothing happens. What am I missing?

Thanks!

**Comment by kg1992** [comment]
Hi.

<https://ag-k.github.io/scratchblocks-html-sample-ja/>

This article was really helpful for me. The page shows usage of renderMatching method.

**Comment by JorgeNachtigall** [comment]
Hi @kg1992 

I've already found it =) But thanks for your reply!
