### ISSUE TITLE
Match blocks before matching 'define' hats

### ISSUE THREAD

**Issue by ninaszymor** [scratchblocks/scratchblocks#311]
The above-mentioned blocks are incorrectly interpreted:

![image](https://user-images.githubusercontent.com/33628387/64780787-33d65180-d559-11e9-9568-a9f8f7eb9c42.png)

They should look like this:

![image](https://user-images.githubusercontent.com/33628387/64780813-42246d80-d559-11e9-9aa7-7a56276897da.png)

I'm raising this issue on behalf of the Raspberry Pi Foundation. We would greatly appreciate if this could be looked at as part of the work Tim has completed for us. Many thanks in advance.

---

http://scratchblocks.github.io/translator/#?lang=pt_br&script=set%20rotation%20style%20%5Bleft-right%20v%5D%0A%0Aset%20size%20to%20(100)%25

http://scratchblocks.github.io/#?style=scratch3&lang=pt_br&script=defina%20o%20estilo%20de%20rota%C3%A7%C3%A3o%20para%20%5Bleft-right%20v%5D%0A%0Adefina%20o%20tamanho%20como%20(100)%20%25

**Comment by tjvr** [comment]
Oh interesting, we interpret them wrong because the "define" block matching kicks in before the block recognition stuff :man_facepalming: That could be very difficult to fix :disappointed:
