### ISSUE TITLE
`stop [all v]` cannot be traslated into Japanese

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#314]
The current implementation cannot translate `stop [all v]` in Japanese as follows.

![image](https://user-images.githubusercontent.com/436237/66100903-c19cde00-e5e7-11e9-86c4-ef5cefa1c55f.png)

`[すべてを止める v]` should be outputted.

**Comment by tjvr** [comment]
This is a combination of #315 and #324; I'm going to close it as a duplicate. Thanks for reporting!
