### ISSUE TITLE
`stop [XXX v]` blocks in Japanese are treated as unknown blocks

### ISSUE THREAD

**Issue by exKAZUu** [scratchblocks/scratchblocks#315]
Related to #314

The following Japanese blocks are treated as unknown blocks.
I expect that this issue is due to no prefix/suffix (like `stop`) in Japanese ...

`[すべてを止める v]` (`stop [all v]` in Japanese)
`[このスクリプトを止める v]` (`stop [this script v]` in Japanese)
`[スプライトの他のスクリプトを止める v]` (`stop [other scripts in sprite v]` in Japanese)

**Comment by exKAZUu** [comment]
@tjvr I want to try fixing this issue. Could you tell me which code I should read? (I need to understand how to parse scratch descriptions and detect `category` of each block.)

**Comment by tjvr** [comment]
Turned out to be a problem in the locale generation, actually!
