### ISSUE TITLE
Documentation of renderMatching options

### ISSUE THREAD

**Issue by HelenFoster** [scratchblocks/scratchblocks#317]
Hi, I had some trouble making my blocks render as Scratch 3. From https://github.com/scratchblocks/scratchblocks/issues/274#issuecomment-464191288, this seems to work:

```scratchblocks.renderMatching('pre.blocks', {style: "scratch3"});```

Are there any other options besides that one?

README.md currently says,

> Then call `scratchblocks.renderMatching` after the page has loaded, which
will render matching page elements to shiny scratch blocks. Its sole argument
is the CSS-style selector for the elements that contain the scratchblocks code.
It uses `pre.blocks` by default.

> `scratchblocks.renderMatching('pre.blocks');`

**Comment by locness3** [comment]
Looking at [the script](https://github.com/scratchblocks/scratchblocks/blob/master/index.js#L126...L132), it seems that the only other options are `inline` and `languages`. I've also [opened an issue](#323) for better documentation.
