### ISSUE TITLE
ScratchBlocks Generator - Translations are not working

### ISSUE THREAD

**Issue by glaukon-ariston** [scratchblocks/scratchblocks#318]
The translation in the generator at http://scratchblocks.github.io/generator/ does not work because the following url is not accessible http://scratchblocks.github.io/js/translations-all-v3.3-min.js

Also, I cannot print the page if the listing is larger than the screen -- it just prints one page with what is visible on the screen at the moment.

Another point. I would like to be able to generate a book out of a Scratch app (basically one huge page with all the code on it). Any idea how to do it?

**Comment by glaukon-ariston** [comment]
I have forked the project and done some changes to the generator code. Now the generator puts the code for the whole project on one web page. Then, I can save the page to a PDF. For the 1979494 project (Space Invaders by ifugu) I get 190 A4 pages.

https://glaukon-ariston.github.io/generator/#project=1979494

**Comment by tjvr** [comment]
Glad you solved it! 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tjvr** [comment]
For anyone else finding this: the generator is deprecated since the release of Scratch 3.0. It's unlikely I'll be able to fix any bugs in it.
