### ISSUE TITLE
ScratchBlocks - Translations are not working

### ISSUE THREAD

**Issue by wwj718** [scratchblocks/scratchblocks#321]
Hi, Translations are not working

https://scratchblocks.github.io/#?style=scratch3&lang=zh_cn&script=repeat%20(10)%0A%20%20%20%20move%20(5)%20steps%0A%20%20%20%20stamp%0Aend%0Arepeat%20(10)%0A%20%20%20%20move%20(10)%20steps%0A%20%20%20%20stamp

![image](https://user-images.githubusercontent.com/3153878/70110257-693a9900-1689-11ea-806e-be8ef758d0c2.png)

**Comment by tjvr** [comment]
You’ll want to click “Translate” to go to the translation page. :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by wwj718** [comment]
Got it , thanks!
