### ISSUE TITLE
Adding more documentation

### ISSUE THREAD

**Issue by locness3** [scratchblocks/scratchblocks#323]
I had to inspect the JS file to know how to set the render style to Scratch 3 instead of Scratch 2 by default.
Would be great to have some more documentation than what's on the README, or if some already exists, point to it on the website and README. I am available to help with this.

thanks for the great project!

**Comment by tjvr** [comment]
Hello 👋 I keep meaning to add this to the Readme, but I’ve been very busy recently. If you think you can improve the Readme, I’d be happy to review a PR!

**Comment by locness3** [comment]
yeah, will consider doing it :)

**Comment by sokunthearithmakara** [comment]
Hi, 
I'm working on a scratch block filter for Moodle. I couldn't figure out how to make Scratch 3 a default and how to render the blocks in languages other than English. Can you please point me to the files that handle these parts? Thank you.

**Comment by tjvr** [comment]
Possible duplicate of #317
