### ISSUE TITLE
Does not support "event_whenstageclicked" block (unique to backdrop)

### ISSUE THREAD

**Issue by azhou4** [scratchblocks/scratchblocks#332]
![Screen Shot 2020-05-21 at 10 28 38 am](https://user-images.githubusercontent.com/31658336/82510432-d6fe5280-9b4d-11ea-967a-70e0737df3c4.png)

http://scratchblocks.github.io/#?style=scratch3&script=when%20stage%20clicked

**Comment by tjvr** [comment]
That's surprising 🤔 Oops!

I think we just need to add this to https://github.com/scratchblocks/scratchblocks/blob/282deb6c53b768e82e04a36f5d10cecea14fbb4e/syntax/commands.js#L503-L510 and then rebuild the translations. Would you care to open a PR for the former? :-)

**Comment by azhou4** [comment]
Thanks @tjvr , can definitely open a PR. What's the "selector"? Not too familiar with that parameter.

**Comment by tjvr** [comment]
I believe they’re taken from the Scratch 3 source code; try searching for one of the other selectors? :-)

**Comment by azhou4** [comment]
Is it possible that selectors are Scratch 2 specific [()?](https://en.scratch-wiki.info/wiki/Scratch_File_Format_(2.0)/Block_Selectors) I can't seem to find selectors in my Scratch 3 JSON output. I am not familiar with Scratch 2.

**Comment by tjvr** [comment]
Looks like it is indeed `EVENT_WHENSTAGECLICKED` :-)
https://github.com/LLK/scratch-l10n/search?q=event_whenstageclicked&unscoped_q=event_whenstageclicked

**Comment by tjvr** [comment]
Fixed in #333
