### ISSUE TITLE
(:: control loop) causes error

### ISSUE THREAD

**Issue by apple502j** [scratchblocks/scratchblocks#346]
`(:: control loop)` on Scratch 3 mode raises error: `Uncaught TypeError: e is undefined`

This is caused at scratch3/blocks.js#L509

Analysis by @kenny2github :
> so that just means lastChild is sometimes not defined even when children.length is nonzero
> which means, children.length is nonzero while lines.length is zero

**Comment by Kenny2github** [comment]
Seen on https://en.scratch-wiki.info/w/index.php?title=Snap!_(programming_language)&oldid=254257#First_class_procedures
