### ISSUE TITLE
Error with |SVG| <use ns:href,,, in Chrome

### ISSUE THREAD

**Issue by DarDoro** [scratchblocks/scratchblocks#348]
SVG "use" element can have only hard coded attribute names
_href_
or
_xlink:href_

Any other values do not display correctly.

```
<svg version="1.1" width="114" height="41">
<defs>
 <path d="M1.504 21L0 19.493 4.567 0h1.948l-.5 2.418s1.002-.502 3.006 0c2.006.503 3.008 2.01 6.517 2.01     3.508 0 4.463-.545 
    4.463-.545l-.823 9.892s-2.137 1.005-5.144.696c-3.007-.307-3.007-2.007-6.014-2.51-3.008-.502-4.512.503-4.512.503L1.504 21z" 
  fill="#3f8d15" 
  id="greenFlag">
 </path>
</defs>
<use ns1:href="#greenFlag"  xmlns:ns1="http://www.w3.org/1999/xlink"/>
</svg>
```

_setProps(el, props)_ or _symbol(href)@draw.js_ is affected.
"xlink:" can be removed at all or setAttributeNS should be called with fully qualified name, not "key.slice(6)"

Edit:
This code 
`setAttributeNS("http://www.w3.org/1999/xlink", "href", "#greenFlag")`
works in pure Chrome JS. 
Embedded in Discourse (VDOM) it build non working entry
`<use ns1:href="#greenFlag"  xmlns:ns1="http://www.w3.org/1999/xlink"/>`

SVG now require only "href=...".

**Comment by tjvr** [comment]
I’m not sure I understand. The SVG generation code has been working for a long time. What has changed in Chrome? And can you try explaining again how to fix it? Thanks.

**Comment by DarDoro** [comment]
You can see the problem here
https://forum.snap.berkeley.edu/t/how-do-you-get-snap-blocks-on-the-forums/2755/23
Objects referenced with "use href" (green flag) are not shown when embedded in Discourse.

"href" element is now part SVG namespace so no need for fully qualify  it. For backward comaptibility "xlink:href" is still handled.
Also "setAttributeNS(http://www.w3.org/1999/xlink..." has received special treatment in browsers (Chrome at least).
The same code, embedded in Discourse (with kind of VDOM), creates invalid entry (object is not shown)
`<use ns1:href="#greenFlag"  xmlns:ns1="http://www.w3.org/1999/xlink"/> 
`

The simplest solution will be to get rid of "xlink:"
**_draw.js_**
symbol(href) {
       return SVG.el("use", {
        ~~xlink:~~ href,
   ...

**Comment by tjvr** [comment]
Hi, just came across this again! Is this still a problem? How did you fix it in the end?

**Comment by DarDoro** [comment]
I think it will be problem forever...
But I fixed this by bulk editing my copy of  http://scratchblocks.github.io/js/scratchblocks-v3.5-min.js

Fix: 
> The simplest solution will be to get rid of "xlink:"
draw.js
symbol(href) {
return SVG.el("use", {
**xlink:** href,
...
