### ISSUE TITLE
Help understanding readme for languages

### ISSUE THREAD

**Issue by ksdavidc** [scratchblocks/scratchblocks#350]
Forgive what is perhaps a rudimentary question, but I don't quite understand 

> . For example, a translation file that just loads the German language (ISO code de) would look something like this:
>
> window.scratchblocks.loadLanguages({
>    de: <contents of locales/de.json>
>})

Specifically, I don't understand where to place this. So far I have got:

> <script src="scratchblocks-v3.5-min.js"></script>

and 

>    scratchblocks.renderMatching('.msb pre', {
>                 style: 'scratch3',
>                 languages: ['en'],
>             });

working fine for english, but if I add  `['jp'],` or any other language, it doesn't work (naturally). The question is, what do I do from here? I expect I have to add some file that it is looking for, and that I have to generate that file??? Or do I have to edit the js file??

**Comment by tjvr** [comment]
That's right, you would have to generate a new JS file that contains the contents of `jp.json`, wrapped in the `window.scratchblocks.loadLanguages()` bit from that example. I suppose that paragraph is assuming you're using some kind of JS build system that would make this easier. Sorry that the readme's unclear on this!

**Comment by ksdavidc** [comment]
Where would I put that js file? Would I name it translations.js? How would it get called. Again, perhaps elementary questions, but I am a semi-newbie...I think you mean the file would start:

```
window.scratchblocks.loadLanguages({
ja: {
  "commands": {
    "move %1 steps": "%1 ほうごかす",
    ...etc.
```

and end:

`})`

and I would call it using:

```
scratchblocks.renderMatching('.msb pre', {
style: 'scratch3',
languages: ['en', 'ja'],
});
```

**Comment by ksdavidc** [comment]
JS build system?? what does that mean?

**Comment by introkun** [comment]
@ksdavidc it's about kind of Babel, Browserify, Webpack, Grunt and Gulp

**Comment by tjvr** [comment]
I've updated the README since this issue was opened, hopefully that helps!
