### ISSUE TITLE
How do you put sb in html?

### ISSUE THREAD

**Issue by Rendangbike** [scratchblocks/scratchblocks#353]
Instead of downloading the svg version of it, is there a tag that can make it do it?

**Comment by tjvr** [comment]
Hello! 👋  The [HTML](https://github.com/scratchblocks/scratchblocks#html) attempts to clarify this :)

**Comment by Rendangbike** [comment]
but how can i do it?
![Screenshot 2021-02-03 185139](https://user-images.githubusercontent.com/76770572/106743421-f217e080-6650-11eb-831c-5f843f1a0522.png)
it's supposed to give out an undefined block, right?

**Comment by tjvr** [comment]
Try putting some scratchblocks code in the HTML:

```html
<pre class="blocks">
when flag clicked
move (10) steps
</pre>
```

You also need to use some JS to run scratchblocks, put this at the bottom of the `<body>`:

```html
<script>
scratchblocks.renderMatching('pre.blocks', {
  style:     'scratch3',   // Optional, defaults to 'scratch2'.
  languages: ['en', 'de'], // Optional, defaults to ['en'].
});
</script>
```

**Comment by tjvr** [comment]
I've updated the README a little more to try and help clarify!

**Comment by Rendangbike** [comment]
It doesn't seem to work 
![Screenshot 2021-02-05 175823](https://user-images.githubusercontent.com/76770572/107025281-c8d78b80-67db-11eb-8614-f88094038fb3.png)
Maybe just say how to put it?
```html
<scratchblocks>
<!-- scripts go here -->
</scratchblocks>
```
Like that?

**Comment by tjvr** [comment]
You've put the `<pre>` inside the `<script>` tag. You need to move the `</script>` tag to before the `<pre>` tag.
