### ISSUE TITLE
Not rendering?

### ISSUE THREAD

**Issue by sargent-coding** [scratchblocks/scratchblocks#354]
![image](https://user-images.githubusercontent.com/65425469/107519932-d8115d00-6b7e-11eb-9170-db6b29aced11.png)
So, I'm using HTML and the scratchblocks won't load. Here's the code: https://glitch.com/edit/#!/spdblx?path=index.html

**Comment by mxmou** [comment]
The console says `Unknown language: 'de'`. Either remove the language from the call to `renderMatching()` or add the translations file.

**Comment by sargent-coding** [comment]
Yay, it worked!
