### ISSUE TITLE
Scratch 1.4 scratchblocks

### ISSUE THREAD

**Issue by TheSmallyDog** [scratchblocks/scratchblocks#357]
What about adding the 1.4 scratchblocks? It would be so cool :)

**Comment by Chaos-emerald** [comment]
See #358

**Comment by CST1229** [comment]
> it would be cool! but with custom color and shape support. why does it only have 1.4 on the scratchblocks dc bot

By the way, the bot isn't official, I made it. It uses the original* block plugin, sourced from the [1.4 archive forums](https://scratcharchive.asun.co/forums/).
* there was an earlier block "plugin" that used images for pieces of blocks but it doesn't matter

**Comment by apple502j** [comment]
The original scratchblocks is for 1.4, I believe. Not sure if it is still available though.

**Comment by CST1229** [comment]
> The original scratchblocks is for 1.4, I believe. Not sure if it is still available though.

It is - the file is on the [1.4 forums archive](https://scratcharchive.asun.co/forums).

**Comment by FlameyTheRealDeal** [comment]
the problem is we      cant use it

**Comment by CST1229** [comment]
> the problem is we cant use it

I've since made [a website](https://cst1229.github.io/scratchblocks-versions/) which allows using it, alongside other scratchblocks versions.

**Comment by tjvr** [comment]
> Was this closed for a reason?

@CST1229 I probably intended to close this as "won't do".
