### ISSUE TITLE
1.4 style

### ISSUE THREAD

**Issue by Time-dragon** [scratchblocks/scratchblocks#358]
Self-explanatory, if @tjvr could download 1.4 offline editor, he'll see.

**Comment by TheSmallyDog** [comment]
I think he doesn't have to download it, I think there is just a 1.4 scratchblocks SVG needed.

**Comment by TheSmallyDog** [comment]
Well, I downloaded the Scratch 1.4, and took a picture of the blocks. Hope I got all of them :)
![All 1.4 scratchblocks (i hope)](https://i.imgur.com/5LdgWkj.gif)

**Comment by mrjacobbloom** [comment]
You might be able to use the old block plugin instead, depending on what you're trying to do: https://en.scratch-wiki.info/wiki/Block_Plugin_(1.4)

**Comment by TheSmallyDog** [comment]
> You might be able to use the old block plugin instead, depending on what you're trying to do: https://en.scratch-wiki.info/wiki/Block_Plugin_(1.4)

There is a link to it, however I get a This site cannot be reached error.

**Comment by tjvr** [comment]
Unfortunately I don't think this is something I'll ever have time for!

**Comment by mrjacobbloom** [comment]
Looks like the old block plugin was scraped by the wayback machine: http://web.archive.org/web/20131019090601/http://archive.scratch.mit.edu/ext/blocksplugin/blocksplugin.js

**Comment by mrjacobbloom** [comment]
Ooh, Andrew Sun also appears to have grabbed a copy of it, along with the icons: https://scratch.mit.edu/discuss/topic/509970/
