### ISSUE TITLE
Having Scratchblocks on my website

### ISSUE THREAD

**Issue by JackyBorderCollie** [scratchblocks/scratchblocks#361]
Hi, I have tried to render Scratchblocks on my website, but it didn't render. [Here's the code I am using.](https://pastebin.com/raw/eCp5BwQB) I have even put the `js.` file on my website, and nothing happened. Is there something I did wrong?

**Comment by mrjacobbloom** [comment]
Make sure that the scratchblocks file is called `scratchblocks-v3.4-min.js` and is in the same folder as your HTML file
