### ISSUE TITLE
If disambiguation is required in English but not in other languages, the block may appear red

### ISSUE THREAD

**Issue by apple502j** [scratchblocks/scratchblocks#369]
It is possible that block A and block B, both called "do something" in English, is translated "do something" and "do some things" in another language.

Repro steps: `boost.getMotorPosition` and `ev3.getMotorPosition` are identical in English but not in German, causing red block.

**Comment by tjvr** [comment]
Why does this cause an obsolete block? :thinking:

**Comment by apple502j** [comment]
@tjvr Code assumes that one English speccode is mapped to one translation. Which isn't, in this case. So the one defined as a translation in the file shows correctly and others don't.
