### ISSUE TITLE
Could you add a zoom option?

### ISSUE THREAD

**Issue by HunorMarton** [scratchblocks/scratchblocks#376]
Currently you can zoom with CSS transform but that does not actually resize the element, so it can look off, especially for inline elements. Could you add a zoom options that resizes the underlaying SVG's width and height? Or would you accept a PR for that?

**Comment by tjvr** [comment]
Previously discussed in #372.

While my preference is that people solve this themselves with CSS, if that isn’t practical then I don’t have any objection to adding a `scale` option.

**Comment by HunorMarton** [comment]
I added one. Let me know if it fits with your idea: https://github.com/scratchblocks/scratchblocks/pull/379
