### ISSUE TITLE
Lug clipped from bottom of "if", "repeat", etc., when nothing follows

### ISSUE THREAD

**Issue by bennorth** [scratchblocks/scratchblocks#380]
Thanks very much for `scratchblocks` — I'm finding it very useful (details below).

I've come across one hiccup.  If an `if` block is the last thing in the source, the rendering is missing the 'lug' at the bottom.  E.g.,

```
if <> then
```

renders as:

![lug-missing](https://user-images.githubusercontent.com/9059396/129571846-d120eb08-58f2-4cbb-afb1-8a40adfd0d50.png)

(Link: [`http://scratchblocks.github.io/#?style=scratch3&script=if%20%3C%3E%20then`](http://scratchblocks.github.io/#?style=scratch3&script=if%20%3C%3E%20then))

And the same things happens with other "C-blocks": `repeat`, `repeat until`, `if/then/else`.  I did try to investigate, but didn't get very far, sorry.

Thanks for any help you can give.

----

We're using `scratchblocks` in [*Pytch*](https://pytch.org), a bridge system for helping learners move from Scratch to Python.  It's a research project of Trinity College Dublin, and our goal is to let learners make engaging interactive projects in Python, while working in a concurrent Scratch-like world of Sprites and events.  [Example here](https://www.pytch.org/app/suggested-tutorial/qbert).

I found `scratchblocks` perfect for letting us show a "cheat sheet" of how Scratch blocks map to Pytch functions/methods, as in:

![image](https://user-images.githubusercontent.com/9059396/129569489-5ce85fc3-4fc4-4b1b-b6ae-2ec7d38ac228.png)

The bug I'm filing this issue for is causing the `if` block (and others) to look not quite right:

![image](https://user-images.githubusercontent.com/9059396/129570252-3c89e5ce-8d3f-4dd4-b884-9dcd8a979bdd.png)

Not a disaster, but it would be great to get this right!

**Comment by tjvr** [comment]
That sure is a bug! Presumably it was hidden until we fixed the padding 🙈
