### ISSUE TITLE
ESM version

### ISSUE THREAD

**Issue by apple502j** [scratchblocks/scratchblocks#381]
Will there be a pre-built ESM version, in addition to the current UMD bundle version? Overriding global variables do not always work.

I'll try to implement this and will send a PR - is that okay?

**Comment by RedGuy12** [comment]
For one,, ESM would allow `import scratchblocks from "./scratchblocks.js";` to avoid creating global variables.
________________________________

**Comment by tjvr** [comment]
tbh if I was going to do work on this project's infrastrucure, my wish list would be something like:
- set up GitHub Actions to automatically run the tests as part of CI
- automatically check the formatting
- use "modern" JS idioms: switch out `var` for `let` for example
- switch to `for (const item of list)`, probably; we used to use `for (var i=0; ` for performance reasons but this is probably no longer necessary
- we still want to compile everything down to whatever baseline everyone supports these days (although even the ST have dropped support for IE at this point I think??)
- convert everything to TypeScript, probably
- configure an Action that automatically publishes releases to NPM

**Comment by apple502j** [comment]
@tjvr Scratch's support policy is kinda strange. As far as we know, Scratch 3.0 requires at least ES6, and the minimum version is Cr63/FF57. Currently project pages and studios have those requirements.

For other pages? Well... the homepage is still shipped with ES5-Shim and there is still a banner to suggest IE9. ES6 would make some things much easier.

"Cross-platform test" is a much harder job, I suppose. I heard puppetter does support Firefox; not sure for Safari, and even if they do, that'd require a macOS machine.

**Comment by RedGuy12** [comment]
I can help you with these!


________________________________

**Comment by apple502j** [comment]
🤦🏼 @tjvr Turns out we already have ESM version and it was just not published at scratchblocks.github.io... See https://unpkg.com/browse/scratchblocks@3.5.2/build/scratchblocks.min.es.js

**Comment by tjvr** [comment]
Ah, that makes sense!

Yeah, I’d rather steer people away from depending on `scratchblocks.github.io` directly, since it makes updates harder for us.

**Comment by apple502j** [comment]
@tjvr That said, the ESM version still adds global `scratchblocks`; we should change this. Translation also assumes we are `window.scratchblocks`.

**Comment by tjvr** [comment]
Ah interesting. Yeah, we should try not to pollute the window namespace if you’re importing as an NPM package.

It’s still useful to have a version that does, though; not all users will be using NPM, and it’s nice to give them the option of “just import these two JS files”!

**Comment by tjvr** [comment]
Anyone up for figuring out how to execute `npm run fmt` / Prettier as a GitHub action, and fail the PR if any files need updating? :pray:

**Comment by RedGuy12** [comment]
I can do it.


________________________________
