### ISSUE TITLE
It seems say () for () seconds not render correctly

### ISSUE THREAD

**Issue by alexwenbj** [scratchblocks/scratchblocks#386]
for example:
`say (hello) for (2) seconds`
It should be:
<img width="234" alt="sp" src="https://user-images.githubusercontent.com/12047524/132080610-bafb7020-cb26-4e42-9298-10ffc349488e.png">

actually:
<img width="650" alt="snapshot" src="https://user-images.githubusercontent.com/12047524/132080587-8cb16d9c-75a2-4ad5-bde7-e75d83ab9207.png">

**Comment by CST1229** [comment]
You have to use [square brackets] for text inputs.

**Comment by alexwenbj** [comment]
> You have to use [square brackets] for text inputs.
> This was a leftover from 2.0 when text and number inputs looked different, and there was a 3.0 grammar option that made round brackets text inputs, but it was confusing so it was removed.

Got it,thank you so much.
