### ISSUE TITLE
Export scratchblocks as SVG?

### ISSUE THREAD

**Issue by themysticsavages** [scratchblocks/scratchblocks#394]
How would I render text as scratchblocks:
```js
<p class='blocks'>
when flag clicked:<br>
forever:<br>
procrastinate
</p>
<script>
scratchblocks.renderMatching('p.blocks', 
  { 
  style:'scratch3'
  }
)
<script>
```
And then export it as an SVG or PNG. I tried taking the SVG from the HTML, but it gives an entirely black block.

**Comment by themysticsavages** [comment]
It's not that. That was a mistake. If I tried rendering a p block using the wrong class, nothing would show up!

**Comment by pikachub2005** [comment]
Oops, I didn't read the bottom of your question. I don't think svg files are written differently from svg in html, but I'll check it out 🤔

**Comment by pikachub2005** [comment]
![image](https://user-images.githubusercontent.com/74213212/137345050-a24a8f48-a73f-45e0-a277-24b685625414.png)

**Comment by themysticsavages** [comment]
Ah, it works now. Thanks everyone!
