### ISSUE TITLE
strange view when call custom blocks with boolean arg

### ISSUE THREAD

**Issue by alexwenbj** [scratchblocks/scratchblocks#399]
If there is a boolean arg in custom block, when call the custom block, if pass value for it, it can't parse correctly, for example:
<img width="591" alt="" src="https://user-images.githubusercontent.com/12047524/136701638-feac9793-c93c-483e-962a-3451cae1ace1.png">

<img width="583" alt="" src="https://user-images.githubusercontent.com/12047524/136701669-fae9b4d9-d173-4fac-81af-21e2b78a2d7e.png">

no matter how I use the "<" and ">", it can't parse correctly.

**Comment by CST1229** [comment]
You need one `<` on the left.

**Comment by RedGuy12** [comment]
He demonstrated how that doesn't work in the first image.


________________________________

**Comment by alexwenbj** [comment]
Yep, no matter how use the "<" and ">", it doesn't work.

**Comment by apple502j** [comment]
@tjvr This is not related to custom args; any blocks with two arguments next to each other confuses the parser.

```
say (join (1) <(1)=(1)>) // fails
say (join (1) <not <(1)=(1)>>) // works

go [forward v] <(1) = (1)> layers // fails
go [forward v] <not <(1) = (1)>> layers // works
```

![image](https://user-images.githubusercontent.com/33279053/137452969-279cdb2b-3d96-44a7-b05c-3df319fbe2b8.png)

![image](https://user-images.githubusercontent.com/33279053/137453447-0ec72554-7403-4c6c-afb4-42882c9b4d9a.png)
