### ISSUE TITLE
Rewrite code using ES6 syntax

### ISSUE THREAD

**Issue by apple502j** [scratchblocks/scratchblocks#413]
Code is currently written using ES5 syntax. While this works fine, ES6 code is generally easier to read and work with as a developer. It might be worth rewriting the code with ES6 syntax. (Of course, I'll be able to help with this stuff!)

**Comment by tjvr** [comment]
If I had the time, I would totally migrate this project to TypeScript :sweat_smile: 

The trouble with projects like "migrate everything to ES6" is it tends to end up with pull requests that are very hard to review. Do you think there's a way we can mitigate that?

**Comment by apple502j** [comment]
@tjvr One potential way would be to fork the project myself - however that just looks like a fork, and it will eventually become a big PR. However that's probably the best option as an external contributor.

Another option would be to add me as a contributor of this organization/repository, make a branch, and work on that branch. Bugfixes and other neat things can be backported to the main branch, and when the time comes, we can just call the new branch "version 4" or something like that.

**Comment by apple502j** [comment]
@tjvr I'll probably start by forking; when you have time I'd like you to add me to the organization so that I can just use the branches here, but for now forks work.

Does that look fine, or should we do it in other ways?

**Comment by apple502j** [comment]
Not sure how much rewrite we can do with that, though.

One question before I start: should we make this 100% TypeScript, or should we only add typings for the user-exposed parts? Since we're rewriting we could make it 100% TypeScript now if we want to, but I'm afraid that'd require rewriting everything at once. Or we could just type the user-exposed bits (or still use regular JavaScript with separate typing info.)

@tjvr Opinions?

**Comment by tjvr** [comment]
My ideal end-state would be that everything is typed, but that could be a lot of work! I don't have much experience trying to convert an existing codebase from JS to TS -- I don't know how much gradual typing TypeScript supports. If you think just adding typings for exposed parts is pragmatic, then let's do that (would solve #404).

Ideally we'd do things a little bit at a time! Maybe we should start off with some CI checks, if that would make this work easier? We could finish off #391?

When you say "ES6 syntax", what kind of features are you thinking of in particular? Preferring `for (let ... of ...)`? Preferring arrow functions?

**Comment by tjvr** [comment]
No objection to any of those!

I suppose we already transpile code with Babel, so this wouldn't mean adding an additional build step?

Not that I'm opposed to changing it -- I'm not in love with any particular `babel` or `browserify` setup, so feel free to change the build system if you would like. My one request would be that we make sure the build is as fast as possible -- I really like quick iteration times when developing locally!

**Comment by tjvr** [comment]
Skipping the building process for local testing would be great!

I am happy waiting for the Typescript compiler in order to get type safety. Equally, the solution you describe sounds good. But probably, we should just start somewhere, rather than trying to solve everything at once :sweat_smile:

**Comment by tjvr** [comment]
A good first PR might be rewriting all `require` calls into `import` statements?

**Comment by apple502j** [comment]
Nice! I'm currently working on CI setup.

**Comment by tjvr** [comment]
I might start rewriting to use `class` syntax :eyes:

**Comment by apple502j** [comment]
The only difference between `.js` and `.es.js` is that `.js` assigns the global `window.scratchblocks` and `.es.js` does not. We could instruct Rollup to turn `es.js` build into UMD. Note that translations still have to be split because it does not assign a global, but instead loads the translations by calling a method, and it's much easier to have two files than write a Rollup/Babel plugin.

**Comment by tjvr** [comment]
* Replace `Object.assign()` with spread operator `{...}`

**Comment by apple502j** [comment]
@tjvr Okay, I just checked things - we should not use `abc = 1` syntax for class fields; we should use either getter-setter pair (for static) or `this.abc = 1` in constructor (for non-static) fields.

Reason? Well, it appears that the static field syntax got Safari support just one year ago (2021-04) - compare this to Chrome (2019-01) or Firefox (2020-04), same goes for fields (added to Safari in September 2020). Given iOS users can only use Safari-like browsers this is not a good thing.

Other ES7+ APIs:

- Object spread: last-to-impl is 2018-04 Safari
- `Array#includes`: 2015-12 Firefox
- async: 2017-03 Safari
- try-catch optional var: 2018-04 Chrome
- `Promise#finally`: 2018-04 Safari
- `{a, b, ...c} = A`: 2018-04 Safari
- `Array#flatMap`: 2018-09 Safari
- `Object.fromEntries` 2019-03 Safari
- Optional chaining: 2020-03 Safari
- `??`: 2020-03 Safari
- `String#replaceAll`: 2020-08 Chrome
- BigInt: 2020-09 Safari

**Comment by apple502j** [comment]
I'd say ESM bundle should support ES2018 at most.

**Comment by tjvr** [comment]
Does our current Rollup build not take care of transpiling newer syntax down for older browsers? 🤔

**Comment by apple502j** [comment]
@tjvr Babel is disabled for ESM build (intentionally, saves build time and runtime perf)

**Comment by tjvr** [comment]
What does tsc's output usually target? If we switched to TypeScript, would we need both tsc and babel?

**Comment by apple502j** [comment]
TSC should return the same input (just with types stripped). It shouldn't be hard to transpile it though. Although I believe jsdoc-based typing should be fine for this project.

**Comment by tjvr** [comment]
I think I would prioritise goals in the following order:

1. Fast local development (sounds like we get this with ES modules + stable releases of Chrome)
2. Allow writing code using as many modern ES features as we can
3. Fast bundling

That is, I think I'm fine making production bundling slower, since we don't need to do it very often. Would you agree with the list above?

I don't know if there are other tradeoffs here we should be thinking about?

**Comment by tjvr** [comment]
Although to be fair, at least for me, "not having to think about / configure build systems" should be pretty high too 😅

**Comment by tjvr** [comment]
If you think we should restrict ourselves to ES2018 (and nothing later?), maybe that's easiest.

**Comment by apple502j** [comment]
Yeah, another thing to consider is that we do not want bugs only reproducible in prod or dev.

personal opinion: Field syntax is also ugly (looks like undeclared variable assignment) imho

**Comment by tjvr** [comment]
@apple502j I think I misunderstood: looks like static fields `static foo = …` are supported way back to Safari 9, but instance fields `isLabel = true` are much more recent?

In which case I'm fine with changing to `get isLabel() { return true }`, or simply `Label.prototype.isLabel = true`. Does that resolve our dilemma?

It would be good to avoid having to make these types of decisions! Perhaps we should add a lint check that no features newer than ES2018 are used?

Or would that catch my precious object spread syntax? 😅

**Comment by apple502j** [comment]
@tjvr Hmm, I don't think that's right. The WebKit bug report (https://bugs.webkit.org/show_bug.cgi?id=194095) is resolved in 2020-11.

**Comment by tjvr** [comment]
Ugh, you're right: I mixed up static methods with static fields. Sigh.

**Comment by tjvr** [comment]
What do you think we should we look at next?

Should we be using a tool like ESLint to catch syntax that is newer than ES2018 (like static class fields), and/or help catch syntax that is older than that (eg `var`) and needs migrating?

**Comment by apple502j** [comment]
Adding eslint config would certainly be nice! (I don’t think we have the setup for eslint yet, so that would be fun fixing the linters yelling :) @tjvr

**Comment by tjvr** [comment]
Well I figure we'd start with only a couple of rules enabled :see_no_evil:

**Comment by tjvr** [comment]
@apple502j Do you see this as done, or is there more we could do here? :eyes:

**Comment by apple502j** [comment]
I'll work on a bit more stuff soon.

**Comment by apple502j** [comment]
@tjvr For example, here is what I'm doing: banning `Array.join` when we should've used template strings using custom ESLint rules
![image](https://user-images.githubusercontent.com/33279053/174442899-36a77895-d3dd-4b4e-9b53-ef9ba8b465d6.png)
