### ISSUE TITLE
I need the horizontal scratchblocks

### ISSUE THREAD

**Issue by traincrisis** [scratchblocks/scratchblocks#433]
Hello!
I need vector SVGʼs of horizontal scratchblocks.
There is an ScratchJr blocks:
[original-4805904-1](https://user-images.githubusercontent.com/97363059/167285348-95e6beb1-bd73-4833-89b4-d3cc31ad9dea.jpg)
Here https://github.com/LLK/scratch-blocks/ and we have this blocks????

**Comment by tjvr** [comment]
Hey, I'm afraid this isn't something we can help with! This project doesn't support the horizontal ScratchJr blocks.

**Comment by traincrisis** [comment]
_octocat_

**Comment by traincrisis** [comment]
:octocat: :trollface:

**Comment by traincrisis** [comment]
:octocat: :lollipop: :nothing: _crazy cat_ 
krazy kat kok kiki_01

**Comment by CST1229** [comment]
> :octocat: 🍭 :nothing: _crazy cat_ krazy kat kok kiki_01

please stop spamming

**Comment by traincrisis** [comment]
> > :octocat: lollipop :nothing: _crazy cat_ krazy kat kok kiki_01
> 
> please stop spamming
Ok!
I just tested GitHub Emojis.

**Comment by traincrisis** [comment]
ah this is so old I remember this spelling
