### ISSUE TITLE
I need the horizontal scratchblocks

### ISSUE THREAD

**Issue by traincrisis** [scratchblocks/scratchblocks#436]
I need the scratch blocks in vector . this is horizontal blocks,  but i cant see it in vector

**Comment by tjvr** [comment]
I'm sorry, I don't think we can help you.

**Comment by traincrisis** [comment]
OK! but i now try to make it.

**Comment by traincrisis** [comment]
@savaka2

**Comment by traincrisis** [comment]
@traincrisis
