### ISSUE TITLE
How to add a new block

### ISSUE THREAD

**Issue by sfederici** [scratchblocks/scratchblocks#442]
I have a customized version of Scratch, where I added the "FOREVER IF" block back (it is very convenient for my students). I would like to use scratchblocks even for this "new" block. I added it to syntax/commands.js as follows

 ```
   {
    id: "CONTROL_FOREVERIF",
    selector: "doForeverIf",
    spec: "forever if",
    inputs: ["%b"],
    shape: "c-block cap",
    category: "control",
    hasLoopArrow: true,
  },

```

I added it to locales/it.json too, as follows

  `  "CONTROL_FOREVERIF": "per sempre quando %1",`
 
Then, I have run

```
npm upgrade scratch-l10n
npm run locales
npm install
npm start

```

but when I write "per sempre quando" at http://localhost:8000/ the block is still not recognized.

What did I miss?

Thanks in advance

**Comment by sfederici** [comment]
I hadn't noticed this errore, when running `npm run locales`

```
file:///Users/stefanofederici/Tutti%20i%20Documenti/Scratch/scratchblocks-master%202/locales-src/build-locales.js:89
    throw new Error("Unknown key: '" + key + "'")
          ^

Error: Unknown key: 'CONTROL_FOREVERIF'
    at translateKey (file:///Users/stefanofederici/Tutti%20i%20Documenti/Scratch/scratchblocks-master%202/locales-src/build-locales.js:89:11)
    at buildLocale (file:///Users/stefanofederici/Tutti%20i%20Documenti/Scratch/scratchblocks-master%202/locales-src/build-locales.js:165:20)
    at convertFile (file:///Users/stefanofederici/Tutti%20i%20Documenti/Scratch/scratchblocks-master%202/locales-src/build-locales.js:222:18)
    at Array.map (<anonymous>)
    at main (file:///Users/stefanofederici/Tutti%20i%20Documenti/Scratch/scratchblocks-master%202/locales-src/build-locales.js:250:58)
npm ERR! code 1
npm ERR! path /Users/stefanofederici/Tutti i Documenti/Scratch/scratchblocks-master 2
npm ERR! command failed
npm ERR! command sh -c node locales-src/build-locales.js
```

**Comment by tjvr** [comment]
Would it work for you to use the standard version of scratchblocks, but add the `:: control` category to each block?

```
forever if <> :: control
  move (10) steps
end
```
<img src="https://user-images.githubusercontent.com/639289/173203954-83abd8f6-2a70-42c1-a0bf-cc6622f1a55e.png" width=160>

**Comment by sfederici** [comment]
I didn't know you could force the category! I think the problem was just the I didn't know scratchblocks enough. Indeed, the right block showed up as soon as I entered the "<" char. Thanks for your help!

**Comment by tjvr** [comment]
No worries. Glad I could help!

**Comment by sfederici** [comment]
Without opening a new issue (I can do that if you think it is worth it), is there a (quick and dirty) way to reduce the height of the 3.0 blocks? I'm using the Scratch Addons, and my students are used to thinner blocks (and they save a lot of space on my slides).

**Comment by tjvr** [comment]
Not sure, sorry! Probably open a new issue if that’s an important question for you.
