### ISSUE TITLE
Bug that I noticed

### ISSUE THREAD

**Issue by qtqgyt** [scratchblocks/scratchblocks#443]
I noticed when i did the scratchblocks to code images function, i did the start sound [pop v] block, and it shown in the image as "startsound [pop v]". Any ideas, or am I correct and is this a bug?... Edit: But it works in 2.0??

**Comment by tjvr** [comment]
I'm not sure I understand, can you provide example code/screenshots?

**Comment by FlameyTheRealDeal** [comment]
maybe he meant the spacing is awkward

**Comment by qtqgyt** [comment]
was fixed in update XD
