### ISSUE TITLE
Reducing height of blocks

### ISSUE THREAD

**Issue by sfederici** [scratchblocks/scratchblocks#444]
Is there a (quick and dirty) way to reduce the height of the 3.0 blocks? I'm using the Scratch Addons, and my students are used to thinner blocks (BTW, thinner blocks save a lot of space on my slides).

**Comment by tjvr** [comment]
Uh, not sure, sorry. You could try tweaking the `draw()` method of `Block`; I'm afraid I can't give you an exact change to make! Maybe this line?

<https://github.com/scratchblocks/scratchblocks/blob/a550f25d81707bdc53c32cd732636b59ad0199f3/scratch3/blocks.js#L424>

**Comment by sfederici** [comment]
> Uh, not sure, sorry. You could try tweaking the `draw()` method of `Block`; I'm afraid I can't give you an exact change to make! Maybe this line?
> 
> https://github.com/scratchblocks/scratchblocks/blob/a550f25d81707bdc53c32cd732636b59ad0199f3/scratch3/blocks.js#L424

I'll give it a try. Thanks for the suggestion.
