### ISSUE TITLE
Redundant space still present

### ISSUE THREAD

**Issue by dmalan** [scratchblocks/scratchblocks#453]
Hi @tjvr, @exKAZUu, just wanted to mention that we still seem to be seeing this symptom with v3.6.0 (and v3.5.2), whereby the `svg` element is ending up with a `height` attribute that's much larger than the SVG's actual height. E.g., 120.5 versus 178:

<img width="536" alt="Screen Shot 2022-04-09 at 1 30 41 PM" src="https://user-images.githubusercontent.com/788678/162585002-d140c800-fd5b-4d77-9353-646027770fb6.png">

This still seems to happen with the v3.6.0 generator, too. E.g., if you export https://scratchblocks.github.io/#?style=scratch3&script=when%20green%20flag%20clicked%0Aask%20%5BWhat's%20your%20name%3F%5D%20and%20wait%0Asay%20(join%20%5Bhello%2C%5D%20(answer)) as a PNG, it saves as the below, with its transparent background quite a bit taller too?

<img width="665" alt="Screen Shot 2022-04-09 at 1 33 07 PM" src="https://user-images.githubusercontent.com/788678/162585074-c371eb64-d408-4804-9462-ca79d74f5e5e.png">

_Originally posted by @dmalan in https://github.com/scratchblocks/scratchblocks/issues/301#issuecomment-1094093303_

**Comment by apple502j** [comment]
Can you reproduce this with the latest commit, just in case? A LOT of code refactor has happened since then.

**Comment by apple502j** [comment]
@dmalan ?

**Comment by tjvr** [comment]
The `preview.blocks` element on that page is absolutely-positioned, so the size seen in your screenshot is expected. It looks like the SVG inside it has the correct size?

**Comment by dmalan** [comment]
Hi @apple502j, @tjvr, thanks so much for the follow-ups. It turns out we were still employing this trick, https://github.com/scratchblocks/scratchblocks/pull/432#issuecomment-1125315800, which resulted in the height difference on our end:

```css
transform: scale(0.675);
transform-origin: 0 0;
```

(Our [scratchblocks.github.io](https://scratchblocks.github.io) experiment was indeed a red herring.) 

But transitioning to

```js
scratchblocks.renderMatching('pre code.language-scratch', {
    scale: 0.675,
    style: 'scratch3'
});
```

has since fixed! Thanks so much for all the help.

**Comment by tjvr** [comment]
That's great to hear! Thanks for sharing :)
