### ISSUE TITLE
Handling of custom block prefixed with "//"

### ISSUE THREAD

**Issue by apple502j** [scratchblocks/scratchblocks#456]
@tjvr How should a custom block prefixed with `//` render? Right now it appears as a comment, even if there is a corresponding definition.

**Comment by tjvr** [comment]
I'm not sure! I'm inclined to suggest that the current behaviour is correct: it makes the scratchblocks language (even more) difficult to parse otherwise. 

Did this come up in a Scratch project, or did you find this through artificial testing? If that distinction makes sense!

What do you think?

**Comment by CST1229** [comment]
> Did this come up in a Scratch project, or did you find this through artificial testing? If that distinction makes sense!

I think several projects use empty`// ()` custom blocks as replacements for Scratch's kinda buggy comments.

**Comment by tjvr** [comment]
Backslash-escaping works for this, right? ie `\// comment`

**Comment by CST1229** [comment]
> Backslash-escaping works for this, right? ie `\// custom comment block`

yes
![](https://user-images.githubusercontent.com/68464103/193335016-37e23a9d-10da-4402-b167-5b7f1eeb106b.png)

**Comment by apple502j** [comment]
Ok, that is a good answer!
