### ISSUE TITLE
Build on website not updated

### ISSUE THREAD

**Issue by apple502j** [scratchblocks/scratchblocks#480]
scratchblocks.github.io is still using the old build. @tjvr

**Comment by tjvr** [comment]
I wrote a PR for that! https://github.com/scratchblocks/scratchblocks.github.io/pull/8

**Comment by apple502j** [comment]
Ah, makes sense.

**Comment by apple502j** [comment]
@tjvr Seems like I lack merge right on that repo. Could you merge that?

**Comment by tjvr** [comment]
I've merged that PR and also updated permissions!
