### ISSUE TITLE
Homepage dropdown has wrong default

### ISSUE THREAD

**Issue by tjvr** [scratchblocks/scratchblocks#482]
Note: this repository doubles as the issue tracker for <http://scratchblocks.github.io>; issues there are deliberately disabled to avoid confusion.

Although the homepage seems to (correctly) default to `scratch3`, the dropdown appears to default to "Scratch 3.0 (high-contrast)". I assume I made some silly typo.

**Comment by mybearworld** [comment]
![An image showing that there are two selected elements.](https://github.com/scratchblocks/scratchblocks/assets/130385691/cf1f47ee-5e8b-4d10-ada3-8ef3be6c1775)
