### ISSUE TITLE
Scratch 3.0 & Scratch 3.0 High Contrast SVGs not editable

### ISSUE THREAD

**Issue by icomputeUK** [scratchblocks/scratchblocks#483]
Downloaded svg's for the above formats cannot be edited.

Illustrator:
<img width="315" alt="2023-06-29_18-53-11" src="https://github.com/scratchblocks/scratchblocks/assets/32702985/c8557120-3eb2-474c-9caf-70e7ce3efaac">

Inkscape:
<img width="1196" alt="2023-06-29_18-55-23" src="https://github.com/scratchblocks/scratchblocks/assets/32702985/a3a2ea2f-8ede-4def-bb76-add903fa627c">

**Comment by tjvr** [comment]
@apple502j This is a result of us using CSS variables, isn't it?

**Comment by icomputeUK** [comment]
It would be really good for them to be editable again. We have thousands of downloads for our free editable Scratch blocks for schools. We create a periodic table of Scratch blocks and group them into categories. Teachers use them for 'unplugged' computing activities and classroom displays.

**Comment by icomputeUK** [comment]
I'm afraid this still isn't working after the issue has been closed. SVGs remain uneditable for Scratch 3.0 blocks.

**Comment by icomputeUK** [comment]
Thanks for the update and release.

Illustrator is good! Just letting you know that images (e.g. green flag and extensions) aren't being rendered.

<img width="677" alt="2023-07-25_13-43-07" src="https://github.com/scratchblocks/scratchblocks/assets/32702985/552b5da5-99ba-4c99-b16e-a112c10d55c7">

<img width="750" alt="2023-07-25_13-43-29" src="https://github.com/scratchblocks/scratchblocks/assets/32702985/e2fece1d-16d1-40b2-b000-980143612a2b">

Many thanks again for your efforts on this.

**Comment by tjvr** [comment]
> Unfortunately it does look to me as though the exported SVGs still don't render in Inkscape, I don't have time to investigate this further now though!

Interestingly the high-contrast SVGs _do_ seem to render okay :thinking:
