### ISSUE TITLE
In "say() for () seconds" block,the data will be treated as variable

### ISSUE THREAD

**Issue by alexwenbj** [scratchblocks/scratchblocks#490]
For example:
Say ( hello ) for (2) seconds
will be rendered as:
![scratchblocks (1)](https://github.com/scratchblocks/scratchblocks/assets/12047524/f471a0bc-3e61-4676-9099-03b73b0a87d9)

the "hello" should be treated as data rather than variable.

**Comment by CST1229** [comment]
Use square brackets.
`say [hello] for (2) seconds`

**Comment by alexwenbj** [comment]
Yes,thank you.
