### ISSUE TITLE
Minimum hat length is too long

### ISSUE THREAD

**Issue by husqwc** [scratchblocks/scratchblocks#508]
The minimum hat block length (implemented in the fix for #261) is too long, actual Scratch blocks can go shorter:
<img width="110" alt="Screenshot 2024-02-19 at 2 37 19 PM" src="https://github.com/scratchblocks/scratchblocks/assets/105561911/cfc8b7a0-09fd-47fb-85e4-6e44be1cbc5b">
![block_3_1_2024-6_03_13 PM](https://github.com/scratchblocks/scratchblocks/assets/105561911/fec01c5d-e428-45c4-948a-2264031c8a74)

(the top one is scratchblocks, while the bottom one is what actually appears in Scratch)

**Comment by tjvr** [comment]
Interesting!

It looks like we never determined the true minimum hat width in Scratch — the commit you linked claims (in the comment) to use an arbitrary value.

How can we determine the correct value? What is the shortest possible hat in Scratch? Is there a language where one of the hat blocks has a very short string?

**Comment by CST1229** [comment]
> It looks like we never determined the true minimum hat width in Scratch — the commit you linked claims (in the comment) to use an arbitrary value.
> 
> How can we determine the correct value? What is the shortest possible hat in Scratch? Is there a language where one of the hat blocks has a very short string?
> 
> (Perhaps the answer is the example you gave, but it's not obvious to me that that example is the true minimum value.)

By modifying scratch-blocks' strings, the shortest normal hat I could get was this:
![image](https://github.com/scratchblocks/scratchblocks/assets/68464103/d72c9c75-ecc3-4996-bce6-e9818df289c4)
(Seems like it's the width of the hat's hat shape + the top right corner.)

And then there's the undefined "red hat block", which is slightly shorter as it does not have the top right corner:
![image](https://github.com/scratchblocks/scratchblocks/assets/68464103/0edf977b-fb19-4b82-8426-c8b8a844f46b)

According to the scratch-blocks source code, [the minimum hat width is 100 units](https://github.com/scratchfoundation/scratch-blocks/blob/ed02f0c01bd43bcf403988182a268262a1586d9c/core/block_render_svg_vertical.js#L1139), which seems to match up more with the red hat block (so I assume the top right corner isn't included in that).
