### ISSUE TITLE
Create texture code from scratch project

### ISSUE THREAD

**Issue by huangganggui** [scratchblocks/scratchblocks#519]
This is very nice  project.

And I have a question:
How to create ~texture~ text code like `when flag clicked` from a scratch project?

For example, I have a project with a block(or some blocks) when flag clicked and saved  to my computer as myproject.sb3. I want to transfer this file to ~texture~ text code  `when flag clicked`

Can some one help me?
Thanks a lot.

**Comment by huangganggui** [comment]
Same to https://github.com/scratchblocks/scratchblocks/issues/501

**Comment by ego-lay-atman-bay** [comment]
What do you mean by texture code?

**Comment by CST1229** [comment]
> What do you mean by texture code?

They probably mean text, as in scratchblocks. There's a library (although it's very old) that can do this: https://github.com/apple502j/parse-sb3-blocks

**Comment by huangganggui** [comment]
@CST1229  Yes, Thanks a lot. 
Looks good. I will try it.
