### ISSUE TITLE
There is a line after extension icons in scratch

### ISSUE THREAD

**Issue by ego-lay-atman-bay** [scratchblocks/scratchblocks#521]
I noticed that in scratch, there is a line after the extension icon in extension blocks.

![block_5_3_2024-2_38_32 PM](https://github.com/scratchblocks/scratchblocks/assets/70973578/2248359c-5ff0-4221-88a0-2282cdd0ea65)

But this is not present in scratchblocks

![scratchblocks (8)](https://github.com/scratchblocks/scratchblocks/assets/70973578/a29e52bd-2542-4c2a-be7b-85fcd1089c27)
https://scratchblocks.github.io/#?style=scratch3&script=stamp

<details><summary>Not gonna lie</summary>
<p>

The real reason I bothered creating this issue, is that I was working on snapblocks, ran into an issue where something I did made extension icons break the rendering, so I looked at where they get added, then realized it really isn't very hard to add the line after the extension icons.

</p>
</details>

Edit: after looking into it a bit more, it seems like you tried to add it, or at least maybe it was working at some point.
https://github.com/scratchblocks/scratchblocks/blob/0ed709ec762f3f917424df42df81026972c52d62/scratch3/blocks.js#L291-L297
(note the `LineView` object)

**Comment by ego-lay-atman-bay** [comment]
Actually I identified the issue. The line is there, but the class that's supposed to set the color doesn't exist (I tested out just setting the stroke to black, and it was magically there).

https://github.com/scratchblocks/scratchblocks/blob/0ed709ec762f3f917424df42df81026972c52d62/scratch3/blocks.js#L140-L151

I think I'm just gonna create a pull request for this, since it's such a simple fix (although I'm going to have to do something different in snapblocks).

**Comment by ego-lay-atman-bay** [comment]
I can't believe I put creating this issue off for a long time, it's literally the easiest fix ever (should I make a pull request?).

**Comment by tjvr** [comment]
> should I make a pull request?

Yes please!

**Comment by ego-lay-atman-bay** [comment]
Created a pull request https://github.com/scratchblocks/scratchblocks/pull/522

**Comment by tjvr** [comment]
@apple502j Can we close this now #522 is merged?

**Comment by ego-lay-atman-bay** [comment]
I'm just gonna close this
